.gitignore, appengine/pageshotpages/css/frame.css, appengine/pageshotpages/frame.html
This is to reinforce the fact that we are looking at the page from
pageshot, not the original site.
=> Make the framed page look like it is on a smaller page

appengine/pageshotpages/collection.html, appengine/pageshotpages/css/collection.css, appengine/pageshotpages/css/frame.css, appengine/pageshotpages/frame.html, appengine/pageshotpages/js/collection.js, appengine/pageshotpages/js/frame.js, appengine/pageshotpages/js/newframe.js, appengine/pageshotpages/main.py
=> r? ianbicking Add "summary" to view selector.

appengine/pageshotpages/collection.html, appengine/pageshotpages/css/collection.css, appengine/pageshotpages/js/frame.js, appengine/pageshotpages/main.py
Also, fix links to tags in comments, and fix the display of the tag
page.
Fixes #160
=> r? ianbicking Remove the empty comment box on the summary page

data/framescripts/make-static-html.js, data/shooter-interactive-worker.js, lib/shooter.js
Mostly snapping, and a couple small fixes @fzzzy
=> Selection snapping

data/shooter-interactive-worker.js
fzzzy: an extraction feature (resulting data not used yet), and a bug fix on selections
=> Capture text and fix offset

data/framescripts/make-static-html.js, data/shooter-interactive-worker.js
Tweaking autoSelect, mostly to get this page to work better: http://www.slideshare.net/Odersky/scala-days-san-francisco-45917092
=> Selection tweaks

data/shooter-interactive-worker.js, lib/shooter.js
Wherein I go through every page linked from Hacker News at one moment, and see how autoSelect works on each, and make nearly all at least passable.  Snapping comments also is interesting.
=> More auto select tweaks

data/capture-selection.js, data/inline-selection.css, data/shoot-panel.html, data/shoot-panel.js, data/shooter-interactive-worker.js, lib/shooter.js, package.json
Copy markup around the selection (including surrounding context), and the selection itself highlighted.
When text is selected at the time you hit the shot button, save the selection and add it to the shot.
Display text selection in the panel (not yet site).
=> Implement text selection capturing.

gulpfile.js
addon/dist/dist/dist/dist etc directories.
=> r? ianbicking Fixes #282 Ignore the addon/dist directory so it doesn't keep creating 

addon/data/extractor-worker.js, addon/data/panel.css, addon/data/shoot-panel.js, addon/data/shooter-interactive-worker.js, addon/lib/main.js, addon/lib/shooter.js, addon/lib/shot.js
Implements multiple clips, and the general clip flow (between visible/selection/auto)
=> r?fzzzy Multiple clips

addon/data/inline-selection.css, addon/data/panel.css, addon/data/shoot-panel.js, addon/data/shooter-interactive-worker.js, addon/lib/shooter.js, addon/lib/shot.js
Makes text clips work.  You can both select text then hit the pageshot button, or after pageshot is started you can select and hit the + button.
=> r?fzzzy Text clips

addon/data/capture-selection.js, addon/data/shoot-panel.js, addon/data/shooter-interactive-worker.js, addon/lib/shooter.js, addon/lib/shot.js
=> r?fzzzy Fix clip panel browsing

addon/lib/shooter.js
=> Record dimensions

server/src/styles.scss, server/src/views/frame.js
Jumping to a clip is not yet supported as location information is not
currently captured.
=> Render text clips in the detail page.

server/src/db.js, server/src/models.js, server/src/server.js, server/src/servershot.js
Add a new server-specific Shot subclass
Add a new db module, that just handles the database connection and some abstract functions for querying (always returning promises)
Change the clip image serving function to use code from the Shot class
=> r?fzzzy Begin refactor of models.js

addon/data/error-utils.js, addon/data/vendor/microformat-shiv.js
I'm not sure we actually want to make changes to this library since it is not our code, but if we're cool with that, this pull request fixes #473.
=> r? ianbicking Fix microformat shiv

gulpfile.js, server/src/server.js, server/src/servershot.js, server/src/views/frame.js, shared/shot.js, static/css/styles.scss
Factor the domain-only URL display into a getter
=> r?fzzzy Add Index page that lists all the shots.

addon/data/annotate-position.js, addon/data/extractor-worker.js, addon/data/framescripts/add-ids.js, addon/data/framescripts/make-static-html.js, addon/data/framescripts/screenshot.js, addon/data/shoot-panel.js, addon/lib/framescripter.js, addon/lib/main.js, addon/lib/multiclip.js, addon/lib/randomstring.js, addon/lib/screenshot.js, addon/lib/shooter.js, addon/lib/user.js, server/src/reactutils.js, server/src/server.js, server/src/views/profile.js, static/css/inline-selection.scss, static/css/panel.scss, static/css/profile.scss
Changes from last week; generally each commit is its own change, File View might not be most useful
=> r?fzzzy Bag o fixes

.gitignore, bin/dumpschema, server/db-patches/patch-0-1.sql, server/schema.sql
Update schema.sql to be accurate of what is created from scratch using our patch files
=> r?fzzzy Update dumpschema to be slightly more helpful

package.json, server/src/server.js
Currently tracks on the server side:
login
unload
clip views, logged in and anonymous
raw clip image views, logged in and anonymous
The client still sends analytics for the shot view, shot list, and
homepage.
=> r? ianbicking Universal analytics

addon/data/shooter-interactive-worker.js, static/css/inline-selection.scss
Also, wait half a second before notifying the user, to prevent the help
message from showing up in the screenshot.
=> r? ianbicking Auto select help message

addon/lib/errors.js, server/src/server.js
ga limits the description to 150 characters.
=> r? ianbicking track exceptions

static/homepage/css/help.css, static/homepage/help.html
=> Add help page

static/homepage/help.html
=> Erase instruction

addon/data/framescripts/.jshintrc, addon/data/framescripts/make-static-html.js, addon/lib/main.js, addon/lib/shooter.js, package.json, server/src/server.js, server/src/servershot.js, shared/shot.js
This implements rewriting resources in the document (replacing each resource with a uuid), collecting the data about those resources, rewriting those uuids when serving through the web frontend, and implementing a very simple proxy to serve up those resources.
=> r?fzzzy Remote resource

.gitignore, server/src/ga-activation.js, server/src/views/frame.js, server/src/views/shell.js
This pull request should be closed first: #922  (I didn't separate things out)
Puts in some Do Not Track code.  Also factors out the GA code from frame.js
=> r?fzzzy Fix 881

.gitignore, addon/data/framescripts/make-static-html.js, server/src/ga-activation.js, server/src/views/frame.js, server/src/views/shell.js
This pull request should be closed first: #923 (I didn't separate things out)
Makes the serialization async, which should keep the add-on from getting the "making Nightly run slowly" error message (but I don't actually know yet if it does).  Tried to take a light touch.  There are several semantically small changes made in early commits, then the actual async change, so reading the commits individually may be useful.
=> r?fzzzy Fix 916

addon/data/framescripts/make-static-html.js, addon/lib/is-public.js
I'm not seeing the topbar now, but I don't know why that would be related to this patch...?
=> r?fzzzy Fix 920

addon/lib/main.js, server/src/views/shell.js, server/src/views/shot-index.js, static/css/styles.scss, static/img/question-mark.svg
Still a bunch to do here, but a start.
Tons of CSS still to be deleted!
=> r?fzzzy Shot index redesign

addon/data/shooter-interactive-worker.js, static/css/inline-selection.scss
Change crosshairs to be fixed, so vertical crosshair still works when scrolled down in page
To be done after PR #1008
=> r?fzzzy Fix 989

static/homepage/css/help.css, static/homepage/help.html
The three images are just broken links right now. I opened #1035 to
track generating and linking those images.
=> r? ianbicking First time slide

addon/data/error-panel.js, addon/data/error-utils.js, addon/data/viewerworker.js, addon/lib/helperworker.js, addon/lib/req.js, addon/lib/screenshot.js
Fixes #972 – finishes removing a few things found on review
=> r?fzzzy Remove cruft

addon/lib/main.js
Currently, using Command-option-control-c. Suggestions for another
hotkey? (How do I know if there is a conflict with an existing key?)
=> r? ianbicking Add hotkey

.ebextensions/00-environment.config, addon/data/annotate-position.js, addon/data/extractor-worker.js, addon/data/framescripts/make-static-html.js, addon/data/shooter-interactive-worker.js, addon/lib/shooter.js, server/src/pages/shotindex/view.js, shared/shot.js, static/css/content.scss, static/css/shot-index.scss, static/js/content-helper.js
A bunch of miscellaneous fixes
=> r?fzzzy Selection fixes etc

addon/data/selector-ui.js, addon/data/shooter-interactive-worker.js, addon/lib/main.js, addon/lib/shooter.js, addon/package.json, server/src/pages/shotindex/view.js, static/css/inline-selection.scss, static/css/styles.scss
=> r?fzzzy Address #1144, put in My Shots reminder

.babelrc, Makefile, addon/data/selector-ui.js, addon/lib/notificationbox.js, bin/_run-docker, bin/run-server, package.json, server/run, static/css/inline-selection.scss
I was expecting to do more today, but events transpired, so this is just a Babel upgrade and a little style tweak.  Doing some other library updates might also be reasonable right now.  I'm guessing only the React upgrade will be painful.
=> r?fzzzy More misc fixes

.jshintignore, package.json
=> Add missing fields to package.json

server/src/pages/admin/model.js, server/src/pages/admin/view.js, static/css/admin.scss
Of course the auth on admin isn't working (to test I commented out the auth), and it probably doesn't render that well (locally I didn't have very interesting records to summarize), but it's a start.
=> r?fzzzy Add a query to the /admin screen that shows retention

README.md, static/homepage/index.html
=> Fix add-on, Node.js, and GitHub typos

.eslintrc, .travis.yml, package.json
Now, we'll fail the Travis-CI build if we introduce any errors reported by **addons-linter**, or if ESLint or sass-lint report any errors.
=> Lint add-on, JavaScript, and Sass files on Travis

addon/data/framescripts/make-static-html.js, addon/lib/headless.js, addon/lib/httpd.jsm, addon/lib/shooter.js, addon/package.json
Some stuff to improve the server form of PageShot for use in some scripts to capture history for Activity Stream
=> r?fzzzy Headless activity stream helper

Makefile, addon/data/annotate-position.js, addon/data/extractor-worker.js, addon/data/selector-snapping.js, addon/data/selector-ui.js, addon/data/viewerworker.js, addon/lib/errors.js, addon/lib/main.js, server/src/contentcheck.js, server/src/exporter.js, server/src/pages/shotindex/controller.js, server/src/servershot.js
Just little stuff, related to #1229
=> r?fzzzy Some fixmes

package.json, server/src/server.js
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1294477
=> Fix quoting in redirect

server/src/pages/shotindex/view.js, static/css/partials/_base.scss, static/css/partials/_layout.scss, static/css/partials/_mixins.scss, static/css/partials/_variables.scss, static/css/shot-index.scss, static/img/glyph-forward-16-white.svg, static/img/glyph-forward-16.svg, static/img/glyph-search-16.svg
=> Shot index style fixes

addon/package.json
=> Tweak the iconURL for the addon XPI

server/src/reactruntime.js, server/src/views/frame.js, static/homepage/index.html
This seems to work, but I can't claim to be the world's foremost authority on favicons.
=> r? ianbicking Fixes #1395 Add a favicon everywhere

server/src/views/frame.js
Ref: https://github.com/mozilla-services/pageshot/pull/1483#discussion_r77924558
=> Remove the onClickGitHub() and onClickRevision() methods

Makefile, README.md, addon/lib/main.js, addon/lib/user.js, bin/run-addon, bin/run-server, server/src/pages/shotindex/view.js, server/src/reactrender.js, server/src/server.js, server/src/views/frame.js, static/css/inline-selection.scss, test/test.js
=> r?fzzzy Little fixes

addon/lib/req.js, addon/lib/shooter.js, docs/METRICS.md, server/src/server.js
Fix #1505, retry upload up to 3 times if there was an error on the attempt
=> r?fzzzy Fix #1506, send body size via Google Analytics and send upload status

addon/data/shooter-interactive-worker.js, addon/lib/req.js, docs/METRICS.md, server/src/server.js
Fix how event options (eventValue, cd0/cd1) are sent to server; previously eventValue was being thrown away.
=> r?fzzzy Fix #1453, add cd0/cd1 dimensions to selection events

README.md, server/src/pages/homepage/view.js
=> Update home page link to deep link to the Page Shot experiment page

server/src/views/frame.js
Ref: https://github.com/mozilla-services/pageshot/issues/1467#issuecomment-248410458
=> Switch Twitter meta tags from 'property' to 'name'

server/db-patches/patch-10-9.sql, server/db-patches/patch-8-9.sql, server/db-patches/patch-9-10.sql, server/schema.sql, server/src/dbschema.js
=> r?fzzzy Fix the bad change to patch-8-9.sql, which left out a DROP COLUMN

package.json, server/src/config.js, server/src/dbschema.js, server/src/server.js
=> r?fzzzy Fix #1571, add /__heartbeat__ and /__lbheartbeat__

addon/lib/main.js, addon/lib/req.js, addon/lib/user.js, docs/METRICS.md, server/src/ga-activation.js, server/src/server.js, server/src/statsd.js
=> r?fzzzy Fix some stuff

Makefile, addon/lib/errors.js, bin/_set_backend_config, bin/_set_package_version, docs/METRICS.md, server/src/server.js, server/src/views/frame.js, static/css/frame.scss
Better by commit, changes aren't related
=> r?fzzzy misc fixes

README.md
We've been sticking little Test Pilot badges in READMEs of the various experiment repositories. Available for you too, if you'd like!
=> Adds Test Pilot badge to README.

server/src/footer-view.js
=> Fix typo for infringement link in footer

server/src/pages/homepage/view.js
=> Update homepage text for Test Pilot button

bin/load_test_exercise.py, server/src/server.js, server/src/users.js, server/src/views/frame.js
Per the email about cohort analysis
=> r?fzzzy Reduce metrics

server/src/pages/shotindex/view.js
=> Set maxlength on shot search input field

addon/data/selector-ui.js, addon/data/shooter-interactive-worker.js, static/css/inline-selection.scss
Fix #1633, indicate the region that would be selected on hover
Add a new class to suppress pointer events but not hide the interface
=> r?fzzzy Fix #1745, use a minimum size on the click autodetect

server/src/views/frame.js, static/css/frame.scss, static/img/share.svg
Also change the color of the Share icon, and remove dos-style line endings on the svg
=> r?fzzzy Fix #1780, keep Share button from overflowing

server/src/pages/shot/share-buttons.js, server/src/pages/shot/view.js, static/css/inline-selection.scss, static/css/partials/_base.scss, static/css/partials/_buttons.scss, static/css/partials/_layout.scss
=> betelgleuse-style-fixes

server/src/pages/metrics/model.js, server/src/pages/metrics/view.js
- Do not filter out shots that seem expired from the shot total count
- Simplify some aliases in queries (not using aliasing in FROM)
- Add a total retention table
=> r?fzzzy Update some metrics queries:

addon/lib/req.js, server/db-patches/patch-11-12.sql, server/db-patches/patch-12-11.sql, server/schema.sql, server/src/dbschema.js, server/src/exporter.js, server/src/pages/leave-page-shot/server.js, server/src/server.js, server/src/users.js
(Has the device_activity commits in it too)
=> r?fzzzy Avoid login loop

.env.dev, addon/lib/main.js, addon/lib/shooter.js, addon/lib/user.js, server/src/config.js, server/src/jobs.js, server/src/pages/metrics/server.js, server/src/server.js
=> r?fzzzy Server management

addon/data/selector-ui.js, addon/data/shooter-interactive-worker.js, addon/lib/main.js, addon/lib/shooter.js, addon/lib/user.js, server/src/ab-tests.js, server/src/config.js, server/src/dbschema.js, server/src/server.js, server/src/users.js, static/css/inline-selection.scss
Unstyled but functional, turned off until it's styled though there's override instructions in #2082
Also little fixes
=> r?fzzzy Ab button

static/css/inline-selection.scss
=> move button off edge

server/src/ga-activation.js
=> r?fzzzy Set window.abTests in the stubbed version of ga-activation.js

addon/data/selector-ui.js, server/src/ab-tests.js, static/css/frame.scss, static/css/inline-selection.scss, static/css/metrics.scss, static/css/partials/_buttons.scss, static/css/partials/_footer.scss
This actually fixes all of my elnath issues
=> add bright button a/b test

.eslintignore, README.md
Follow up #2199.
Remaining:
1. `"main"` in /package.json, need to change to `webextension/background/main.js`? or remove?
2. Not understand the `"build/shot.js",` in webextension/manifest.json, irrelevant entry?
=> follow up for become an WebExtension

.eslintignore, Makefile, webextension/README.md, webextension/background/analytics.js, webextension/background/auth.js, webextension/background/communication.js, webextension/background/deviceInfo.js, webextension/background/loadSelector.js, webextension/background/main.js, webextension/background/senderror.js, webextension/background/takeshot.js, webextension/catcher.js, webextension/manifest.json.template, webextension/selector/callBackground.js, webextension/selector/shooter.js, webextension/selector/ui.js, webextension/selector/uicontrol.js
Gets error catching infrastructure back in place.  Doesn't actually catch all those errors (followup for that in #2241)
=> r? fzzzy or _6a68 Error catching

docs/METRICS.md, webextension/background/analytics.js, webextension/background/main.js, webextension/background/takeshot.js
=> r? fzzzy or 6a68: Refresh metrics

docs/acceptance.md
@clouserw @ianb @dannycoates @6a68
=> add acceptance for shipping in 54

docs/acceptance.md
minor change to add a couple of issues to the acceptance doc...i'm going to self merge this
=> minor acceptance changes

webextension/background/main.js, webextension/background/takeshot.js, webextension/clipboard.js, webextension/selector/shooter.js
fixes #2284 
I moved the notification and tab to be after the copy and report an error if the copy failed.
=> removed 'copied' notification if the copy failed

docs/acceptance.md, webextension/selector/ui.js
=> make selection buttons show up near window bottom

static/css/partials/_large-icon-block.scss
=> fix loading spinner

docs/acceptance.md
=> Fix link in acceptance docs

addon/webextension/background/main.js
=> fix: Redirects new tab to my shots

addon/webextension/background/auth.js
=> store registered status locally

server/src/pages/shot/controller.js, server/src/pages/shot/share-buttons.js, server/src/pages/shot/view.js
fixes #2322
I wasn't sure if we want to strip out all the rich copy code or just remove the button so I started with the latter.
=> removed rich copy button from share panel

addon/bootstrap.js, addon/webextension/background/auth.js, addon/webextension/background/main.js, bin/run-addon
=> Migrate sdk

addon/webextension/README.md, addon/webextension/background/analytics.js, addon/webextension/background/communication.js, addon/webextension/background/loadSelector.js, addon/webextension/background/main.js, addon/webextension/background/takeshot.js, shared/shot.js
and a cleanup commit (not related)
=> Optional bootstrap

static/img/glyph-history-16.svg, static/img/glyph-stop-16.svg
=> Remove xml-stylesheet from SVGs

test/test.js
Resolves https://github.com/mozilla-services/pageshot/issues/2405, allowing the test suite to run more comfortably on older hardware.
=> extend test timeout

README.md
=> readme: Add note about supported firefoxes for --setup-profile

addon/bootstrap.js
=> Observe prefs and control webextension startup and shutdown via a pref

addon/webextension/background/auth.js, addon/webextension/background/takeshot.js, shared/shot.js
The error handling wasn't really working here
=> Better server unavailable error

addon/webextension/background/senderror.js, locales/en-US/webextension.properties
@6a68 this is still provisional but probably worth merging. I kind of want to review some of the old keys b/c they're not very didactic.
=> provisional addon strings

addon/webextension/background/main.js
=> copy icon for notification

addon/bootstrap.js
Addresses review comments from #2471.
=> Update bootstrap.js per review comments

addon/webextension/background/main.js
fixes #2415 
IDK if we want to add the cookies permission, but if we do this works.
=> ensure auth when visiting /shots from addon

addon/webextension/selector/ui.js, static/css/inline-selection.scss
Add tabindex to the buttons on that page
Change pre-selection buttons to <button> so Enter/Space works
Remove flex from the buttons and put it into an interior element to make styling work
=> Focus pre-selection iframe when it is displayed

addon/webextension/selector/uicontrol.js
=> scrolled selection bug fix

addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js
=> added tabId to ui toggle

addon/webextension/background/auth.js, addon/webextension/background/communication.js, addon/webextension/background/takeshot.js, addon/webextension/catcher.js, addon/webextension/clipboard.js, addon/webextension/selector/callBackground.js, addon/webextension/selector/shooter.js, docs/METRICS.md, shared/shot.js
(Got a lot bigger than I expected)
=> Exception fixups

addon/webextension/background/main.js
=> made unshootable page errors human readable

addon/webextension/background/senderror.js
=> WIP remove user urls from sentry data

server/src/footer-view.js, server/src/pages/legal/model.js, server/src/pages/legal/server.js, server/src/pages/legal/view.js, server/src/server.js
This is a fix for Update privacy links.
Fixes #2476.
=> Fix-#2476-change privacy page to privacyLink

addon/webextension/background/selectorLoader.js
=> run the selector js on document_end instead of document_idle

addon/webextension/background/main.js, addon/webextension/manifest.json.template, addon/webextension/selector/ui.js
=> use webextension downloads api

server/src/server.js
=> added X-Content-Type-Options: nosniff

addon/webextension/background/senderror.js, addon/webextension/selector/shooter.js
=> put url sanitizing in the right context

addon/bootstrap.js
Dropping the QI seems to work.
I suggest not merging this, until we get a clean try run, just in case ;-)
=> Fix WebExtension Initialization in packaged builds.

server/src/servershot.js
=> assert data: urls have a png header

server/src/config.js
This fixes half of #2549, the image shows in the page, but the svg rendering is still broken
=> restore contentOrigin config

addon/bootstrap.js, addon/webextension/background/main.js
=> Delay WebExtension startup

addon/bootstrap.js, addon/webextension/background/auth.js
=> set registrationInfo from old addon

locales/en-US/webextension.properties
Based on some of the feedback received so far from localizers on potentially confusing strings.
=> Improve localization comments

server/src/server.js
Is this all we need here?
fixes #2466
=> force content-type image/png for /images

addon/webextension/background/analytics.js, addon/webextension/background/auth.js, addon/webextension/background/communication.js, addon/webextension/background/deviceInfo.js, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/background/senderror.js, addon/webextension/background/takeshot.js, addon/webextension/catcher.js, addon/webextension/clipboard.js, addon/webextension/domainFromUrl.js, addon/webextension/makeUuid.js, addon/webextension/onboarding/slides.js, addon/webextension/selector/documentMetadata.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, addon/webextension/selector/util.js, addon/webextension/sitehelper.js
the quick fix for #2633 is to go back to `window`. Otherwise feel free to grind on `unloadModules`
=> go back to window.*

addon/webextension/assertIsTrusted.js, addon/webextension/background/analytics.js, addon/webextension/background/auth.js, addon/webextension/background/communication.js, addon/webextension/background/deviceInfo.js, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/background/senderror.js, addon/webextension/background/takeshot.js, addon/webextension/catcher.js, addon/webextension/clipboard.js, addon/webextension/domainFromUrl.js, addon/webextension/makeUuid.js, addon/webextension/onboarding/slides.js, addon/webextension/randomString.js, addon/webextension/selector/callBackground.js, addon/webextension/selector/documentMetadata.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, addon/webextension/selector/util.js, addon/webextension/sitehelper.js
=> changed window assignments to this in the content-scripts

addon/webextension/background/auth.js
json instead of FormData but :man_shrugging: 
fixes #2661
=> use json instead of x-wblahhh for xhr requests

server/src/pages/shot/view.js, server/src/pages/shotindex/view.js
=> Sets character limit on shot title (WIP)

server/src/servershot.js
=> delete image files on delete

addon/webextension/background/main.js, addon/webextension/onboarding/slides.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js
Should fix eslint errors causing build failure on CircleCI
=> Fix linter errors

package.json, server/src/pages/leave-screenshots/server.js, server/src/pages/leave-screenshots/view.js, server/src/pages/shot/controller.js, server/src/pages/shot/server.js, server/src/pages/shotindex/controller.js, server/src/reactrender.js, server/src/server.js
fixes #2331 and other important routes
=> added csrf protection

addon/webextension/background/takeshot.js
=> set favicon of shot

addon/webextension/background/auth.js
=> fixed isOwner check on getAuthInfo

addon/webextension/icons/icon-welcome-face-without-eyes.svg, addon/webextension/manifest.json.template, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, static/css/inline-selection.scss
Some small fixups to the JavaScript in #2676
=> Youwenliang ux updates

addon/webextension/icons/icon-welcome-face-without-eyes.svg, addon/webextension/manifest.json.template, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, static/css/inline-selection.scss
Add the smiley face to the "during shot page" according to the UX spec.
https://mozilla.invisionapp.com/share/GWBAFJBE2
=> Add the smiley face

package.json, server/src/pages/shot/model.js, server/src/pages/shot/view.js, server/src/proxy-url.js, server/src/server.js
Annoyingly, the `filename` portion is non-trivial to encode but there's an existing module to handle it.
fixes #2600
=> use Content-Disposition for downloading images

addon/webextension/background/communication.js, addon/webextension/background/main.js, addon/webextension/onboarding/slides.js
See #2699 for discussion and steps to reproduce the bug.
=> 2699 fix terms and privacy urls

server/src/server.js
"25mb should be enough for anybody"
closes #2229
=> set upload size limit to 25mb

server/src/servershot.js
=> 404 images from expired shots

server/src/pages/shot/model.js
=> use proxy url for favicon on shot page

addon/webextension/background/selectorLoader.js
=> Fix testIfLoaded so it can see when a load is in progress

addon/webextension/background/main.js
Previously Screenshots was not disabled on shot pages
Also simplify a regular expression slightly
=> Fix the detection of shot pages

addon/webextension/background/main.js, addon/webextension/catcher.js
Quiet the watchFunction calls in tabs.onUpdated and tabs.onActivated, that should never pop up a message
=> Add a quiet parameter to watchFunction to match watchPromise

.eslintrc.yml, addon/webextension/log.js, bin/.eslintrc.yml, server/src/browser-send-event.js, server/src/config.js, server/src/server.js, test/.eslintrc.yml
=> Handle ESLint no-console rule

server/src/pages/homepage/view.js
=> Remove duplicate meta description in head

addon/webextension/selector/uicontrol.js, docs/METRICS.md, server/src/ab-tests.js, server/src/share-buttons.js, static/css/inline-selection.scss
(Do it right this time)
* Document tests are finished
* Remove code referring to autoOpenSharePanel
* Remove code and styles referring to styleMyShotsButton
* Put all old tests in deprecatedTests
=> Actually fix #2796, disable all active A/B tests

CHANGELOG.md, addon/bootstrap.js, addon/webextension/background/main.js, package.json
Fixes related to the Talos regressions tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1361792.
These changes have already been reviewed by kmag: https://reviewboard.mozilla.org/r/136348/diff/2#index_header
Fixes #2800, fixes #2813.
=> Perf fixes

server/src/pages/shot/view.js, server/src/server.js
Fixes #2774, making Twitter cards work again
Invalidates #2805
=> remove robots.txt and replace with meta noindex

static/css/partials/_theme.scss, static/css/shot-index.scss, static/img/spinner.svg
=> fix shot index trash flicker

static/css/inline-selection.scss
=> fix onboarding text for long strings

docs/METRICS.md
=> Fix #2837, add some more details about Sentry to the metrics documentation

addon/bootstrap.js
This reverts commit 81a567a99c83b52cbd61c606e279da308e3d77df.
=> Revert "Start WebExtension immediately"

server/src/pages/homepage/view.js
=> Fix GitHub and Twitter links on homepage

server/src/pages/homepage/view.js
=> Removing bottom bit of landing page

addon/webextension/onboarding/slides.js, addon/webextension/selector/ui.js
Fixes #2928, for fixing #2897 we still need to reverse and move the arrows.
Not sure if this is the best way to do this since I'm copying the same code into multiple places, but I also couldn't find a utility file to add a function there maybe.
=> Set lang and dir to html tags

static/css/frame.scss
=> fix select list

static/css/inline-selection.scss
=> better align RTL buttons

addon/webextension/background/auth.js
Fixes #2919, migration issues
Fixes #2902, haywire notification on startup
=> Defer the migration until local registration info has been fetched

server/src/pages/shotindex/view.js, server/src/share-buttons.js, static/css/frame.scss, static/css/shot-index.scss
This is a work-in-progress for #2771 and #2880(?).
=> Fix #2771, #2880

addon/webextension/selector/ui.js
Fixed them to the top as a placeholder while I figure out the best way to reposition them.
Fix for #2918
=> Change button position if not in viewport

addon/webextension/background/deviceInfo.js, addon/webextension/background/main.js, addon/webextension/domainFromUrl.js, addon/webextension/selector/documentMetadata.js, server/src/ga-activation.js, server/src/pages/shot/controller.js, server/src/pages/shot/view.js, server/src/pages/shotindex/controller.js, server/src/server.js, server/src/servershot.js, shared/shot.js, static/js/wantsauth.js
=> Sets limits in regexes

server/src/config.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js
=> hide search

server/src/pages/shot/view.js
=> hides 'copy image text' option if text capture is disabled

addon/webextension/onboarding/slides.js, docs/METRICS.md
=> closes onboarding modal on clicking outside

addon/bootstrap.js
Manually clear the startup cache for the screenshots addon whenever the startup or shutdown reasons indicate we are upgrading or downgrading.
Hopefully this will fix #3027.
I'll push to Try this evening and add to the original bug.
I don't know under what circumstances the StartupCache call could throw. I can look at that if needed, but the addon code itself [doesn't bother](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/Extension.jsm#733-735). /me shrugs
=> Fix #3027, manually clear StartupCache

server/src/pages/homepage/view.js
Small change - Go To My Shots on the homepage has a text cursor and not a pointer.
=> change cursor style

server/src/pages/homepage/model.js, server/src/pages/homepage/view.js
=> Fix 3005: Hides download firefox button

addon/bootstrap.js
Addressing comments from https://reviewboard.mozilla.org/r/149122/ as well as aswan's remark in #teamaddons that we don't need to clear cache on shutdown
=> Address Firefox review feedback on StartupCache changes

npm-shrinkwrap.json
I'm pretty sure if we use npm 5+, then the simple presence of this file will do what we want.
=> Add npm shrinkwrap; fixes #2430

server/src/config.js, server/src/linker.js, server/src/pages/homepage/view.js, server/src/pages/shotindex/view.js, server/src/reactrender.js, server/src/reactruntime.js, server/src/server.js
=> modifies staticLink to host static assets in CDN

README.md
=> Add a link to the research Google docs folder

addon/webextension/onboarding/slides.js
This was probably broken by merging 10.3.0 into master
=> Fix terms l10n id

static/css/inline-selection.scss, static/css/partials/_animations.scss
Some small animation changes suggested by @youwenliang
=> shot preview animation changes

locales/en-US/server.ftl, npm-shrinkwrap.json, package.json, server/src/l10n.js, server/src/pages/creating/model.js, server/src/pages/creating/view.js, server/src/pages/homepage/view.js, server/src/pages/leave-screenshots/model.js, server/src/pages/leave-screenshots/server.js, server/src/pages/leave-screenshots/view.js, server/src/pages/metrics/view.js, server/src/pages/not-found/model.js, server/src/pages/not-found/view.js, server/src/pages/shot/controller.js, server/src/pages/shot/server.js, server/src/pages/shot/time-diff.js, server/src/pages/shot/view.js, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/server.js, server/src/pages/shotindex/view.js, server/src/reactrender.js, server/src/reactruntime.js, server/src/server.js, server/src/share-buttons.js
Still debugging some build issues, but the .ftl file is mostly baked. @flodolo comments welcome! We can land the server.ftl file before the rest of the code, if the localizers need to get started now for the 55 release date.
Major outstanding todos:
- figure out what to do about timediffs (likely replace relative times with absolute dates)
- check these strings against the master approved list of strings
=> localize server

server/src/pages/shot/view.js, server/src/server.js
Update the original link format (Bugzilla #1381189)
I added a ga event to track outbound clicks, is this the correct way to do it?
=> Update original URL link handling

server/src/pages/homepage/view.js, server/src/pages/shot/view.js, static/css/frame.scss, static/css/shot-index.scss
=> fix some ui nits

docs/export-to-firefox.md
Trying to reflect reality a little more closely.
Maybe we should leave the export_mc.py docs? I've run into issues with its fancier behavior, so I basically use it like `diff`.
=> Update export docs

CHANGELOG.md, bin/generate-commit-log, circle.yml, docs/server-release.md
will merge over to server-prod after this lands...
=> Server release

addon/bootstrap.js, locales/en-US/webextension.properties
This will also require some changes to Firefox which I will put on the bug.
=> Bug 1366026 - add an item to the library panel that opens shots page

server/src/server.js
=> Correctly get language headers from request (#3152)

server/src/server.js
=> Fix #3185, make authentication cookies long-lived

server/src/server.js
=> Handle redirects in calls to /proxy

static/css/inline-selection.scss
=> Tweak button container CSS

server/src/l10n.js, server/src/server.js
=> When initing l10n, cache contents of FTL files, not user locale (#3170)

docs/METRICS.md, server/src/pages/shot/view.js
=> Adds an event for non-owner click on original url

static/css/inline-selection.scss
=> update shot preview save icon

addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js
=> remove duplicate drawWindow call for shot preview

bin/require.pip, server/src/server.js, server/src/servershot.js, test/server/clientlib.py, test/server/test_shot_put_auth.py
Because of a bad test for the UPDATE's success, file updates were committed
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1384817
=> Fix detection of a bad UPDATE in response to PUT

server/src/pages/homepage/view.js
Fixes homepage Mozilla footer logo is 404 #3223
=> Fixes homepage Mozilla footer logo 

server/src/server.js
=> Remove server /timing route 

server/src/pages/shotindex/view.js, static/css/shot-index.scss
=> animate deleting shots on my shots

addon/bootstrap.js
I think everything's synchronized here, except shutdown is invoked without any way to pass back a callback or promise, so we might still see annoying issues with improper shutdown (that other bug)
hopefully fixes #3257
=> Synchronize startup code more carefully

addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js
=> remove high DPI shot capture for full page

server/src/pages/homepage/view.js
=> make homepage footer more consistent

bin/load_test_exercise.py, bin/load_test_exercise_images.py, docs/performance-testing.md, package.json, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/server.js, server/src/pages/shotindex/view.js
Unfortunately I wasn't able to reproduce the speed problems, despite many attempts. Also stage doesn't have the same performance characteristic. This patch is based on the assumption that the problem is the database query (which seems like the one thing that will run differently in production than stage).
=> Myshots perf

server/src/pages/shotindex/view.js, static/css/partials/_animations.scss
=> clean up my shots loader

.gitignore, bin/build-prod-xpi, bin/build-scripts/update_manifest.py, docs/xpi-release.md
Also fix a small bug with updating the manifest version
=> Fix #3313, create script to create release-ready XPIs

server/db-patches/patch-19-20.sql, server/db-patches/patch-20-19.sql, server/schema.sql, server/src/dbschema.js
Also updates schema.sql with version 19 (because I forgot ./bin/dumpschema --record for that version)
=> Add an index on data.deviceid to speed up My Shots

CHANGELOG.md, addon/bootstrap.js, package.json
Bringing the fix for #3323 over to the export branch for uplift
=> Export shutdown fix

server/src/reactrender.js
=> properly escape seperators

.gitignore, bin/build-prod-xpi, bin/build-scripts/update_manifest.py, docs/xpi-release.md
Also fix a small bug with updating the manifest version
@ianb r?
=> Fix #3313, create script to create release-ready XPIs (#3316)

addon/bootstrap.js
=> Deal with lack of MOZ_PHOTON_THEME on 57+

CHANGELOG.md, package.json
I thought rearranging the changelog would be helpful to identify changes. 
I'm not sure if it's an entirely good changelog either, like it might include reverted changes.
=> HOLD Update version to 16 and consolidate add-on changelog

docs/METRICS.md, server/src/pages/homepage/view.js, server/src/pages/shot/view.js
=> add utm and events to home

server/src/servershot.js, shared/shot.js
Fixes #3297 (Bugzilla: 1388781)
=> validate original url

package.json, server/src/l10n.js
See https://github.com/projectfluent/fluent.js/issues/61#issuecomment-323153344
=> Update fluent-langneg to 0.1.0

server/src/reactrender.js
Fix for [1389704](https://bugzilla.mozilla.org/show_bug.cgi?id=1389704)
=> seperate script blocks

circle.yml, package.json, server/src/config.js, server/src/server.js
Adds coverage reports like https://3190-26788257-gh.circle-artifacts.com/0/tmp/circle-artifacts.ZM5y72r/server-coverage/lcov-report/index.html for development and CI.
=> Add option for tracking server side code coverage

static/css/settings.scss
=> fix fxa email display

.env.dev, server/src/config.js
Fixes #3373 and a misspelled `ENABLE_ANNOTATIONS`
=> enable features for testing

addon/bootstrap.js
This is @gijsk's changes from #3404, plus the change @kmaglione suggested
=> Fix review feedback for screenshots 16.0.0

addon/webextension/background/takeshot.js, addon/webextension/selector/shooter.js, server/src/server.js
Fix for #3217 
This converts the binary blob back to base64 before saving it to the database, which is what I'm a little unsure about. @ianb
=> Send image to server in binary

server/src/pages/settings/controller.js, server/src/pages/shot/controller.js, server/src/pages/shotindex/controller.js
=> Send exceptions to raven when alert is called

docs/METRICS.md, static/css/frame.scss, static/css/partials/_variables.scss
=> fix disappearing buttons

server/src/pages/settings/controller.js, server/src/pages/settings/view.js, server/src/server.js
=> fix disconnect button

server/src/server.js, server/src/users.js, test/server/clientlib.py, test/server/test_auth.py
Adds server auth tests and fixes a few 500 errors.
r? @ianb
=> Add server auth tests

server/src/server.js
Update app to reflect server config per bugs https://bugzilla.mozilla.org/show_bug.cgi?id=1383836 and https://bugzilla.mozilla.org/show_bug.cgi?id=1385176
r? @ianb
=> server: remove the /proxy endpoint

static/css/settings.scss
Fixes #3402 and makes the settings page responsive
=> make settings page responsive

server/src/pages/settings/view.js, server/src/server.js
=> display fxa avatar

server/src/pages/homepage/view.js
See discussion in #3407. Hopefully the simple fix will be good enough
=> Move homepage CSS above JS to avoid FOUC

server/src/middleware/csrf.js, server/src/server.js, test/server/test_csrf.py
csrf header validation for bug 1388783
=> validate csrf headers

server/src/pages/homepage/controller.js, server/src/pages/homepage/view.js, static/js/UITour-lib.js
We should confirm with @Fischer-L that this is the right way to do this
=> Add Mozilla.UITour call to homepage, for #3411

CODEOWNERS
Copied this right from Test Pilot
=> Add flod as string owner. Fixes #3369

server/src/footer-view.js
=> replace faq with kb link

package.json
I'm hoping this fixes the `fresh` security issue
=> Update express dependency

server/src/middleware/csrf.js, server/src/pages/shot/server.js, server/src/ravenclient.js, server/src/responses.js, server/src/server.js
A couple privacy issues, and making some server-side page exceptions nicer by including request information.
=> Raven cleanups

addon/bootstrap.js, test/test.js
Tracking for export. See [bug 1405166](https://bugzilla.mozilla.org/show_bug.cgi?id=1405166)
=> [Do not merge] Fix #3549, remove code that checks for system-disabled pref

server/src/pages/shot/view.js
=> Floor a potentially fractional width. (#3541)

addon/webextension/background/selectorLoader.js
=> Load scripts at document_start.

server/src/pages/metrics/model.js, server/src/pages/metrics/view.js
Remove Add-on Version from /metrics. Closes #3609
=> Remove Add-on Version from /metrics. Closes #3609

docs/export-to-firefox.md
fixes #2822 without doing additional work :-P
=> link to talos / treeherder walkthrough

server/src/config.js, server/src/db.js
=> Use pg connection pooling.

addon/webextension/domainFromUrl.js, shared/shot.js, static/js/wantsauth.js
=> Update domain name regex to allow `-` and `_`.

addon/webextension/selector/uicontrol.js
=> Allow full size downloaded shots.

README.md
=> Mention .env.dev in README.

static/css/inline-selection.scss
=> fix rtl save icon alignment

locales/en-US/server.ftl, package.json, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/server.js, server/src/pages/shotindex/view.js, server/src/servershot.js, static/css/shot-index.scss, static/img/arrowhead-left-16.svg, static/img/arrowhead-right-16.svg
=> Paginate My Shots

addon/bootstrap.js, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/selector/ui.js
Since we're going to allow uploads when third-party cookies are disabled, this finishes off #3574.
Two open TODOs in the code. Otherwise, seems to work for me :beers:
=> Use download only mode if 'never remember history' is checked

server/src/pages/shotindex/view.js, static/css/shot-index.scss
=> Fix page number style and add guard against NaN.

addon/webextension/icons/help-16.svg, addon/webextension/manifest.json.template, addon/webextension/selector/ui.js, static/css/inline-selection.scss
fixes https://github.com/mozilla-services/screenshots/issues/3693
=> style tweaks for dl only ui

addon/bootstrap.js
@chenba Mind giving this a try? After applying this patch, dev edition should still complain about an "unknown scalar", but should otherwise work
=> Fix #3718, send a response after incrementing counts

addon/webextension/buildSettings.js.template
=> Bump pixel limit to 10000.

test/test.js
=> Opt out of webdriver click in Selenium tests.

server/db-patches/patch-21-22.sql, server/schema.sql, server/src/dbschema.js, server/src/server.js
=> Fix #3530, support domains up to 253 characters long

addon/webextension/selector/ui.js
=> Add left margin to selection frame to handle doc width < viewport width

addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js
=> Download shot when Enter is pressed in download only mode.

addon/webextension/background/senderror.js, addon/webextension/background/startBackground.js
=> Move start time for error timer into startBackground.

server/src/pages/shot/editor.js
=> Fix #3709 and fix #3669, remove oversampling of canvas

addon/webextension/selector/ui.js, static/css/inline-selection.scss
=> Use download only notice style for cropped image warning.

addon/webextension/background/startBackground.js
=> Remove unnecessary icon path for page action.

server/src/reactrender.js
This code is run literally without any babel translation, and shouldn't use fancy JavaScript
=> Use var instead of let in reactrender

addon/webextension/background/main.js
=> Add paste symbol for image copy notification.

addon/webextension/manifest.json.template
=> Add copy.svg path to manifest template.

addon/webextension/selector/ui.js
=> Add titles to preview overlay buttons.

CHANGELOG.md, package.json
add 25.0.0 changelog
bump current version in dev to 26.0.0
=> Bump version in master

addon/webextension/background/analytics.js
=> Suppress analytics server errors in addon. (#3820)

server/src/pages/shot/editor.js
Fixes #3405 
I haven't been able to test this because the save button works locally.
=> Fix save button

server/src/pages/shot/editor.js, static/css/frame.scss
Fixes #3678 
Fixes #3680 - I moved the tools to the top-left of the page. Felt like they looked awkward in the middle.
=> Annotation UI update

.nsprc
See #3841 for a followup to update moment
=> Fix CI tests by suppressing warning about moment

addon/webextension/selector/ui.js, server/src/pages/shotindex/view.js, static/css/inline-selection.scss, static/css/shot-index.scss
=> Use <img> instead of background image for My Shots and overlay buttons.

addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, static/css/inline-selection.scss
=> Add cancel button to deactivate Screenshots.

.nsprc, addon/bootstrap.js, addon/webextension/background/analytics.js, addon/webextension/background/main.js, addon/webextension/background/takeshot.js, addon/webextension/selector/ui.js
Pull request #3846 covers the firefox peer feedback, other two commits have already been reviewed & landed in master
=> Export updates

addon/bootstrap.js, addon/webextension/background/analytics.js, addon/webextension/background/main.js, addon/webextension/background/takeshot.js, addon/webextension/selector/ui.js
Changes:
* use 1 message to send telemetry scalars
* escape all reserved chars, not just quotes
* remove needless thenable
* simplify anyMatches
* prefer Map to obj literal
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1419148#c13
=> Firefox peer feedback for 25.0.0 release

static/css/inline-selection.scss
=> Fix rtl preview buttons.

server/src/pages/shotindex/view.js
=> Do Not Show Pagination Content When Total Shots Count is Undefined

static/css/frame.scss
=> Remove browser vertical scrollbar in edit view.

server/src/ab-tests.js, server/src/server.js
A/B tests that are for unauthenticated users must be set on any request, since for authenticated users the A/B tests are sent and recorded on register/login.
A/B tests that are for unauthenticated users must be marked as appliesToPublic
=> Fix #3893, apply A/B tests to unauthenticated users

server/src/server.js
=> Set image CORS access for site origin.

locales/en-US/server.ftl, server/src/pages/shot/editor.js
=> Localize annotation page.

server/src/pages/shot/controller.js, server/src/pages/shot/view.js, static/css/frame.scss
=> Add survey link

addon/webextension/selector/shooter.js
=> Do not copy while copying

server/src/pages/shot/editor.js
=> Revert canvas img crossOrigin attr to Anonymous.

addon/webextension/selector/uicontrol.js
=> Use keydown event for copy to clipboard because of MacOS.

package.json
=> Update svgo to latest.

bin/build-scripts/bundle_dependencies
=> Build prod React bundles.

server/src/servershot.js
=> Use old thumbnail when applicable.

server/src/pages/shotindex/view.js, shared/thumbnailGenerator.js, static/css/shot-index.scss
=> Use fixed height for thumbnail container

server/src/servershot.js
=> Add thumbnail to unedited list to stop removal.

server/src/pages/shot/view.js
=> Remove right margin on image only download icon

addon/webextension/selector/shooter.js
=> Hide UI frame unless server error occurs

server/src/reactrender.js
=> Remove l10n messages from JSON response.

addon/webextension/selector/uicontrol.js
=> Fix math on distance calculation for starting drag selection

addon/webextension/selector/ui.js
=> Use an object url for the preview image.

addon/webextension/background/analytics.js, addon/webextension/background/main.js, addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js
Fix #3900 
Note that user timings are still sent.
=> Do not send events while in private browsing.

addon/webextension/selector/ui.js
=> Negate body shift in scroll-proof fashion.

locales/en-US/server.ftl, server/src/pages/shot/view.js, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, server/src/servershot.js, static/css/shot-index.scss
=> Add never expire indicator to My Shots

static/css/shot-index.scss
=> Update style for indefinitely saved symbol.

locales/en-US/server.ftl, server/src/pages/shot/view.js
=> Change l10n string id.

addon/webextension/selector/uicontrol.js
=> Remove dimension limits when copying full page shots

server/src/pages/shot/editor.js, static/css/frame.scss
=> Annotation fixes

addon/bootstrap.js, addon/webextension/background/analytics.js, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/background/senderror.js, addon/webextension/selector/ui.js, locales/en-US/webextension.properties
Fixes #3996, and includes some refactoring as well.
Might be more readable commit-by-commit, rather than as unified diff.
=> Disable uploads for ESR or when upload-disabled pref is set

addon/webextension/selector/uicontrol.js
=> Prevent Enter from performing two actions.

server/src/pages/shot/editor.js, static/css/frame.scss
=> Annotations - disable save button on click

locales/en-US/server.ftl, server/src/pages/shot/editor.js
=> Add tooltips to crop buttons

server/src/config.js, server/src/pages/shot/editor.js, server/src/pages/shot/model.js, server/src/pages/shot/view.js, server/src/server.js
=> Save as jpeg on annotation edit if image is greater than configured limit

addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js
=> Download or copy the preview image when possible.

addon/webextension/background/takeshot.js
=> Replace shot creating url with view url from addon

server/src/pages/shot/editor.js
=> Annotations - prevent crop-box resizing against borders

locales/en-US/server.ftl, server/src/pages/shot/editor.js
=> Update l10n ids of annotataion crop buttons

docs/METRICS.md
Fixes #4037 and reduces shame level.
=> Document copy to clipboard metrics.

addon/webextension/selector/ui.js
Fixes #4008
Removes the fix for #2918.  Whatever changes made in the interim must've made that fix unnecessary.
=> Remove a button position fix that's no longer needed.

addon/bootstrap.js, addon/webextension/background/auth.js, addon/webextension/background/communication.js, addon/webextension/background/main.js, addon/webextension/background/startBackground.js
Pretty sure I've shaved off all the relevant bits.
Fixes #3844.
=> Remove pageshot migration code

addon/bootstrap.js, addon/webextension/selector/uicontrol.js, shared/shot.js, test/addon/browser.ini
Two refactorings in mozilla-central affected our code. See the individual commit messages for details.
One of the refactorings touched raven.js. I'm not sure if eslint can auto-rewrite that particular line or not, but it'll be something to watch for in future exports.
=> Upstream changes

server/src/pages/shot/controller.js, server/src/pages/shot/view.js, static/css/frame.scss, static/img/edit-highlight.svg
=> highlight annotations button

circle.yml
Because root on CircleCI is a jerk.
=> Change Xvfb display number.

addon/bootstrap.js, addon/webextension/background/analytics.js, server/src/pages/shot/controller.js, server/src/pages/shot/editor.js, server/src/pages/shot/view.js
=> Fix lint issues.

circle.yml
Missed this bit in previous change to display number.
=> Update an arg for xvfb cmd in CircleCI.

docs/export-to-firefox.md
=> Clarify l10n export process

circle.yml
Maybe nohup is a little more reliable than start-stop-daemon?
=> Try using nohup to start Xvfb

circle.yml
=> Run Nightly in headless mode.

README.md
Because pg-patcher is checking for an error message in English
=> Update Postgres info in README.

server/src/pages/shot/editor.js, static/css/frame.scss
Fix #4015 
Fix #3994 
Fix #4046
=> Annotation Updates

test/test.js
=> Add auto selection shot Selenium test.

addon/webextension/background/main.js, addon/webextension/background/takeshot.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js
=> Show loader animation on truncated full page download/copy

addon/webextension/background/analytics.js, addon/webextension/selector/uicontrol.js
=> Include onboarding slides in user timing measurements

.nsprc
=> Ignore https://nodesecurity.io/advisories/566 with .nsprc

.nsprc, package.json
=> Upgrade convict, which upgrades moment

test/test.js
=> Use done cb in Selenium tests to fail faster

locales/en-US/server.ftl
* `#` for comment sigil
* no more sections,`##` for section comments
* equal sign on empty value
CC @pike
=> Switch en-US FTL file to new syntax

server/src/pages/shot/editor.js
=> Add loader for annotation saves

.env.dev
=> Set LOCALHOST_SSL to true in .evn.dev.

server/src/pages/shot/editor.js, server/src/pages/shot/view.js, static/css/frame.scss
Fix #4134 
Fix #4117 
Fix #3934
=> Annotations - P1

addon/webextension/selector/uicontrol.js
=> Remove two extra handlers and add more conditions around ctrl+c.

server/src/pages/shot/editor.js
=> Remove event listeners after cancelling edit mode

server/src/pages/shot/editor.js
=> Disallow drawing on header.

server/src/caching.js, server/src/server.js
=> Do not cache static files if revs mismatch.

server/src/pages/shot/editor.js, static/css/frame.scss
Fix #4171 
Fix #4100 
Fix #4136
=> Annotations Fixes

server/src/pages/shot/editor.js, static/css/frame.scss
=> Delete some CSS for Annotations

server/src/pages/shot/editor.js
=> Restore a CSS class b/c the crop tool needs it.

shared/shot.js
I couldn't test it yet, but this should fix issue #4197. Maybe someone can test it?
=> Standard ISO 8601 date for filename, fixes #4197

server/src/pages/shot/view.js
Fixes #3654 
We should wait for approval from legal
=> change flag to survey

test/addon/.artifacts/.gitignore, test/test.js
=> Add download shot Selenium test.

test/test.js
=> Add more post-test reset code for addon button test.

static/css/frame.scss
=> Center the image in the editor.

.env.dev
=> Set SET_CACHE to false in .env.dev

shared/shot.js
=> Remove some code around the favicon url.

shared/shot.js
=> Use string functions instead of regex for isUrl.

addon/webextension/selector/ui.js
Fixes #4217 
Related to #3907 and #3972
=> Calculate left and top margin of selection frame with left and top of doucument element and body

addon/webextension/background/takeshot.js, addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js, server/src/pages/shot/controller.js, server/src/pages/shot/model.js, server/src/servershot.js, shared/shot.js
Fixes #2593, specifically [this comment from kmag](https://github.com/mozilla-services/screenshots/pull/2471#discussion_r109269102).
This does not contain any changes to `deepEqual`, since there isn't anything obviously wrong with it.
=> Rename asJson to toJSON. (#2593)

server/src/users.js
=> Use crypto.timingSafeEqual.

static/css/frame.scss
=> fix extra shadow

server/src/pages/shot/editor.js
=> Move middle button click check.

server/src/pages/shot/editor.js
=> Scroll shot in crop mode

bin/_run-docker
...because it doesn't seem to work in dev.
=> Undo run-docker change for NODE_ICU_DATA.

docs/METRICS.md, server/src/pages/shot/editor.js
=> Add per-drawing events

server/src/pages/shot/editor.js
Fix #3669 
I haven't tested this on standard DPI screens, but the image quality should remain unchanged. The oversampling will only happen on HiDPI screens.
=> Oversample canvas on HiDPI screens

addon/webextension/onboarding/slides.js, addon/webextension/selector/ui.js
=> Set display CSS property on iframes

addon/webextension/selector/ui.js
=> Fix a Width to Prevent Horizontal Scrolling on Selection Frame.

test/test.js
=> Use backend env var in Selenium tests

server/src/pages/shot/editor.js
=> dismiss color picker on click

locales/en-US/server.ftl, server/src/pages/shot/editor.js, server/src/pages/shot/view.js
=> Add l10n title messages for image edit button and colors.

server/src/pages/shot/view.js
=> Handle empty shot title on edit save.

test/test.js
=> Restore tests now that they pass on Nightly.

test/test.js
=> Remove comments in tests.js that are no longer applicable

server/src/pages/shot/controller.js, server/src/pages/shot/view.js
Fixes #3255 along with some React warnings on a prop type mismatch.
=> Display created time and title after expire time save. 

test/test.js
=> Open page action panel before clicking screenshots in tests.

server/src/pages/shot/view.js
=> Update og:title when shot title changes.

static/css/settings.scss
=> Fix FxA UI

server/src/config.js
=> Fix #4255, correct env var names in config.js

server/src/server.js
=> Allow CSP to be disabled in dev env.

addon/webextension/clipboard.js
Fixes #4269 
Related to #4148, with the same fix.
=> Fix URL clipboard copy for certain sites.

.circleci/config.yml
=> Remove NODE_ENV from CircleCI build job.

docs/METRICS.md, server/src/pages/shot/editor.js
=> Include color in color picker event

locales/en-US/server.ftl, server/src/pages/settings/view.js
=> Localize Settings Page

static/css/frame.scss
=> Center color picker

package.json
=> Upgrade to latest query-string 5.x.x

bin/export_mc.py, test/addon/browser_screenshots_ui_check.js
Some stuff that came up during our Firefox export
=> Release fixes

addon/bootstrap.js, addon/webextension/log.js
=> clean up log.js

server/src/pages/shot/view.js
=> Use component state to highlight edit button on client side.

server/src/pages/creating/controller.js, server/src/pages/creating/model.js
Fixes #4010 
Do not merge this until the fix for #3995 is released in the addon.
=> [HOLD] Remove the unnecessary pushState() in /creating

.nsprc
This .nsprc change seems to fix the build locally for me. We'll see if this fixes circle-ci, too.
=> Fix #4397, Add open nsp issues to nsprc

README.md
=> Add more info to README.

server/src/server.js
=> Remove redundant OAuth sub-scopes under profile scope

Makefile, README.md, addon/webextension/selector/shooter.js
Lots of things didn't work... but I think they already didn't work? I couldn't actually get Visible to work. But selection seems okay, including on The Verge.
=> Chrome prototype changes

Makefile, addon/webextension/background/selectorLoader.js, addon/webextension/selector/uicontrol.js, server/src/pages/shot/color-picker.js, server/src/pages/shot/crop-tool.js, server/src/pages/shot/drawing-tool.js, server/src/pages/shot/editor.js, server/src/pages/shot/highlighter-tool.js, server/src/pages/shot/pen-tool.js, shared/selection.js, static/css/frame.scss, test/unit/selection.js
=> Refactor Annotations.

renovate.json
=> Make renovate work less.

server/src/pages/shot/drawing-tool.js, server/src/pages/shot/editor.js, server/src/pages/shot/highlighter-tool.js
=> Have the editor save the drawing once.

server/src/pages/shot/editor.js
=> Set globalCompositeOperation on context not canvas.

server/src/pages/shot/crop-tool.js
- Also fix the width of right hand side background div.
Fix #4456 and #4455
=> Prevent dragging of crop div.

bin/build-docker-image, bin/release-version, server/src/config.js, server/src/dbschema.js, test/server/test_file_management.py
=> Skip DB downgrades.

server/db-patches/patch-22-23.sql, server/db-patches/patch-23-22.sql, server/db-patches/patch-23-24.sql, server/db-patches/patch-24-23.sql, server/schema.sql, server/src/dbschema.js
=> Add watchdog submissions DB table migration SQL.

bin/run-addon
@ianb Think I've got it this time. Mind taking a look?
=> Correctly loop over possible firefoxes

shared/selection.js, test/unit/selection.js
=> Ensure positive width and length from selection.

package.json
=> Switch to uglify-es for ES6+ support.

server/src/pages/shot/view.js
=> Fix #4411, make expiration date buttons focusable

server/src/server.js
=> Fix #4012, removing potentially sensitive information on title update

addon/webextension/onboarding/slides.js, addon/webextension/selector/ui.js
=> Fix #4537, overriding iframes' inherited background-color

addon/webextension/selector/ui.js
=> Fix #4510, resize right-side background div

addon/webextension/selector/ui.js
=> Correcting commit made via pull request #4563

CHANGELOG.md
Copying changelog for 31.5.0 back into master.
=> Update changelog for 31.5.0; Fixes #4562

.env.dev, package.json, server/src/config.js, server/src/server.js, server/src/watchdog.js, test/server/test_file_management.py
=> Submit shot image to Watchdog on save.

server/src/middleware/csrf.js, server/src/server.js, server/src/watchdog.js
Fix #4378, #4379 
Note that #4529 should be merged before this.
=> Handle Watchdog Callback Requests

addon/webextension/selector/shooter.js
While it's true that the 10,000 pixel limit can be ignored for downloaded or copied shots (#4570), we still need to respect the canvas limit of 32,767 pixels on a side.
I initially fixed this in the Selection creation step in the `onClickFullPage` method of `uicontrol.js`, but the problem popped up again with downloading and copying, probably because `removeDimensionLimitsOnFullPageShot` doesn't consider canvas limits when resetting the selection dimensions. This patch centralizes canvas limit checks to a single spot, the `captureToCanvas` method in `shooter.js`. I've deliberately leaned towards easy readability, rather than terseness. Open to suggestions.
Fixes #4596.
=> Ensure full-page selection fits into a single canvas

locales/en-US/server.ftl, server/src/pages/shot/color-picker.js, server/src/pages/shot/editor.js, server/src/pages/shot/text-tool.js, static/css/frame.scss, static/img/annotation-text.svg
It's initial commit. Creating PR for discussion and early feedback
=> Annotation - Add Text Tool

server/src/watchdog.js
=> Fixes #4610 - Remove temporary debug log output.

server/src/pages/shot/text-tool.js
The draggable attr on the outer div was affecting the click behavior on the editable content div.  Stopping the click/mouse event bubbling didn't make a difference.
=> Fixes #4622 - Stop using draggable attr.

server/src/reactruntime.js
=> Switch to ReactDOM.hydrate for React 16+

server/src/pages/shot/crop-tool.js, server/src/pages/shot/drawing-tool.js, server/src/pages/shot/text-tool.js
=> Shrink text input toward its center and image.

server/src/pages/shot/drawing-tool.js, server/src/pages/shot/highlighter-tool.js, server/src/pages/shot/pen-tool.js
=> Clear only dirty areas of a canvas.

docs/export-to-firefox.md
=> Update export-to-firefox docs

server/src/pages/shot/text-tool.js
=> Fixes #4680 - Text width should not extend beyond 5px inside canvas

server/src/pages/shot/editor.js
=> Stop using decimal dimensions

package.json
=> Upgrade geckodriver to 1.12.0

Makefile, static/homepage/install-test-local.html
=> Suppress logging the actual curl command to avoid leaking the autograph edge token

server/src/config.js, server/src/watchdog.js
Fixes #4725 
I will also file a PR in the cloudops repo to set the value in dev.
=> Add special shot hostname config for Watchdog

.circleci/config.yml
=> Disable code coverage in CI

bin/require.pip, docs/METRICS.md, locales/en-US/server.ftl, server/src/pages/shot/model.js, server/src/pages/shot/view.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, server/src/server.js, static/css/frame.scss, static/css/shot-index.scss, static/img/icon-heart.svg, test/server/clientlib.py, test/server/pglib.py
=> Replace shot expiration with favorites for FxA users

docs/acceptance.md
=> update acceptance for fxa

server/src/watchdog.js
=> Add logs to Watchdog callbacks

server/src/watchdog.js
=> Add shot id to Watchdog submission

server/src/pages/shot/view.js
=> Use Time Difference Amount Not Timestamp when Saving Expiration on Unfavorite

server/db-patches/patch-24-25.sql, server/db-patches/patch-25-24.sql, server/src/dbschema.js, server/src/server.js, server/src/servershot.js
Given the date and version number we can later deduce the Firefox channel
(I don't think we're splitting the database migration from the code currently, but I can't exactly remember?)
=> Start #4748, add Firefox major version to the shot table

addon/webextension/selector/uicontrol.js
=> Fix #4731, displaying selection's coordinates when resizing

server/src/pages/shot/view.js
=> Restore expiration info on shot page

addon/webextension/selector/ui.js
=> Reverse preselection button tab order

addon/webextension/background/takeshot.js
=> Stop capturing favicon URL

docs/testing-the-api.md, server/src/pages/shot/model.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, shared/shot.js, static/css/frame.scss, static/css/shot-index.scss
=> Remove favicon from UI and shot model

static/css/frame.scss
=> Fix #4663, make "Color Picker" and "Cancel" button visibly focusable

server/src/pages/shot/text-tool.js
=> Fix #4652, bring textbox into view when refocusing

locales/en-CA/server.ftl, locales/en-GB/server.ftl
=> Fix shot expiration l10n strings for en-CA and en-GB

server/src/config.js, server/src/watchdog.js
=> Exclude shots from Watchdog based on Firefox version/channel

webextension/selector/uicontrol.js
=> Fix #4731 (2), displaying selection's dimensions when resizing

bin/generate-commit-log
=> Fix #4650, ignore Renovate commits in generate-commit-log script

server/src/footer-view.js, server/src/pages/not-found/view.js, server/src/pages/shot/footer.js, server/src/pages/shot/view.js, server/src/pages/shotindex/footer.js, server/src/pages/shotindex/view.js
=> Use page specific footer on shot and My Shots

static/css/partials/_header.scss
=> Fix #4895, prevent button contents from moving when clicked

docs/METRICS.md, server/src/pages/shot/view.js
=> Use download url on shot when accessed from mobile browser

server/src/watchdog.js
=> Catch Watchdog upstream error

server/src/config.js, server/src/watchdog.js
=> Add logs only mode for Watchdog integration

docs/watchdog.md
=> Add Watchdog documentation

server/src/server.js
=> Add content CDN to connect-src in CSP

server/src/pages/shotindex/view.js, static/css/shot-index.scss
=> Handle thumbnail sizes with synced icon

server/src/pages/shot/controller.js, server/src/pages/shot/view.js
=> Fix copy shot button race condition

webextension/background/auth.js, webextension/background/main.js, webextension/sitehelper.js
=> Delay device id generation until upload

package-lock.json, server/src/errors.js, server/src/users.js
=> Handle fetch HTTP errors in FxA responses

package-lock.json, package.json, server/src/config.js, server/src/server.js, test/server/test_file_management.py
Fixes #4753 
Set `DEBUG=universal-analytics` to debug UA: https://github.com/peaksandpies/universal-analytics/blob/master/HISTORY.md#0417
=> Upgrade universal-analytics to 0.4.17

server/src/l10n.js, server/src/middleware/l10n.js, server/src/reactruntime.js
Reverts mozilla-services/screenshots#4994
=> Revert "Set useIsolating option for Fluent bundles"

.circleci/config.yml
Ugh, what a pain, but this works now!
=> Fix Postgres CircleCI installation

server/src/reactrender.js
=> A11y - Add lang attribte to <html> tag

server/src/pages/homepage/view.js, server/src/pages/shot/view.js, server/src/reactruntime.js
DRY: Moved all meta-viewport declarations to a single location.
Fixes: #5018
=> Removed unneeded maximum-scale parameter.

docs/METRICS.md, locales/en-US/server.ftl, server/src/ad-banner.js, static/css/onboarding.scss, static/css/partials/_header.scss, static/css/partials/_variables.scss
=> Make the "sign in or sign up" clickable in banner

requirements.txt, test/server/test_file_management.py
Hopefully the tests will all pass with these two changes.
=> [WIP] Fix tests?

locales/da/server.ftl
=> Fixes da locale's bannerUpsell anchor tag order

server/src/ad-banner.js, server/src/promotion-strategy.js
#5275 is the followup for proper text and localization.
=> Start #5248, create site-wide notice about the shutdown

webextension/background/analytics.js
This also turns off sending events for the session if it ever gets a 410 Gone response
=> Fix #5277, turn down logging if sendEvent fails

server/src/promotion-strategy.js
I wanted to make this configurable, but passing that information via the backend, into React, into the client during hydration, started to touch lots of files. Hardcoding it keeps it simple.
=> Fix #5299, disable shutdown header

webextension/background/main.js, webextension/background/startBackground.js, webextension/manifest.json.template, webextension/onboarding/slides.js
TIL Can't specify 'option' as a webextension hot key.
Just go with ctrl + shift + s, which will be command + shift + s on mac.
=> Fixes #5089 - Screenshots keyboard shortcut

locales/en-US/server.ftl, server/src/ad-banner.js
(I believe it's the right thing to do this as two strings to account for the `<b>`, but I'm not 100% sure)
=> Add reviewed language for the site banner

server/src/server.js
This reverts commit cbddd7ca767f8d09c36a02dc755c4df932e5a463.
=> Revert "Implement /api/tmp-do-not-ship-set-all-indefinite"

webextension/background/startBackground.js
This applies to the migration code that runs on startup
=> Fix #5332, cache startup server check

locales/en-US/server.ftl, server/src/pages/hosting-shutdown/model.js, server/src/pages/hosting-shutdown/view.js
(Ignore test failures, CircleCI has been acting up lately)
=> Fix #5275, add text to /hosting-shutdown page

test/test.js
This probably won't fix anything, but might make the failures clearer
=> Speculative help for CircleCI failures

webextension/background/main.js, webextension/background/startBackground.js
This removes all the code to check the server, including checking if we want to open the proactive shutdown notice.
This does not remove the supporting code for adding the library button and My Shots (the code exists but isn't called).
=> Fix #5381, remove Library and My Shots links

server/src/pages/homepage/page.js, server/src/pages/homepage/view.js, server/src/server.js, static/js/homepage-tour.js, webextension/background/main.js
This makes the homepage static, and removes dynamic endpoints from the server.
It doesn't remove code, just stubs out the entry points into all that code.
=> Static homepage

renovate.json
I guess I'm assuming just removing the file is enough...?
=> Remove renovatebot

README.md
PR to update ReadMe with 'Getting to know Code' section links fixed and 'Clarifying the future of Firefox Screenshots' link added
=> Fixes #5420 - Update ReadMe
