mozilla-services/screenshots

data/extractor-worker.js, data/framescripts/make-static-html.js, data/shooter-interactive-worker.js, data/vendor/Readability.js, lib/main.js, lib/shooter.js, package.json, run
@fzzzy – This contains a bunch of updates.
The primary feature is that it autoselects content when you make a shot.  It uses the Readability library to hint at what is most interesting.  It then finds block elements that are contained fully within the viewable screen, and uses them as the boundary.  There's a noticeable performance hit, but I'm not sure exactly why.  The function that should be doing the work (`autoSelect()`) doesn't seem to take much time on the wall clock.
It should improve snapping some, I wasn't calculating positions correctly (getBoundingClientRect returns viewport-relative numbers), but it still doesn't feel awesome.  Not sure if there's too many snap lines or something else.
We'll have to open a bug about the Readability.js changes, to get them upstream.  We should …
=> Auto select readable

data/shooter-interactive-worker.js, lib/main.js, lib/shooter.js
@fzzzy Fix #181, track in-place updates of location.
Avoid sending null selections (a partial fix - we shouldn't let people update the selection with a click and no drag)
=> Fix #181, track in-place updates of location.

addon/data/panel.css, addon/data/shoot-panel.js
It looked strange on the right side because it overlaps with the scroll bar, so I moved it to the left side, but it still looks a little strange there, too.
=> Move the delete button so it doesn't scroll with the clip. Fixes #338

server/src/server.js
I think this is right...I'm able to use PageShot locally after changing the cookie name to `user`. Previously, it would return 401s whenever I brought up the recall panel. The server function does `req.userId = cookies.get("user", {signed: true})`, too.
=> r? ianbicking Set the `user` cookie during registration

addon/data/shoot-panel.js
This does work, but the onblur handler consumes the first click event, so you have to click twice on the + to add a new clip. I can't seem to have the blur event and the click event both fire. It does prevent you from losing your comment, though.
=> r? ianbicking Fixes #517 Save comments on blur.

addon/package.json
I for some reason left the port type as "string" when it should have been int. This resolves it.
=> httpServerPort type is integer, not string

README.md
Use pageshot.dev.mozaws.net instead of pageshotpages.appspot.com.
=> Point README directly to the pageshot site.

Makefile, server/src/linker.js, server/src/pages/admin/controller.js, server/src/pages/admin/model.js, server/src/pages/admin/page.js, server/src/pages/admin/server.js, server/src/pages/admin/view.js, server/src/reactrender.js, server/src/reactruntime.js, server/src/server.js, server/src/users.js, server/views-docs.md, static/css/admin.scss
This pull request should be closed first: #921 (I didn't separate things out)
This adds an admin page.  There's a problem with FxA, so right now there's a hardcoded list of deviceIds that can access the page.
I also implemented a new pattern for isomorphic pages, described in [a document](https://github.com/mozilla-services/pageshot/blob/admin-page/server/views-docs.md) – the idea being that we could use this for other pages on the site, but it would be easiest to experiment on the admin page.  The dynamic imports make me sad, but otherwise I feel okay about the pattern.
=> r?fzzzy Admin page

.eslintignore, .eslintrc, addon/.eslintrc, addon/data/annotate-position.js, addon/data/error-utils.js, addon/data/extractor-worker.js, addon/data/framescripts/add-ids.js, addon/data/framescripts/make-static-html.js, addon/data/framescripts/screenshot.js, addon/data/selector-snapping.js, addon/data/selector-ui.js, addon/data/selector-util.js, addon/lib/helperworker.js, addon/lib/main.js, addon/lib/shooter.js, addon/lib/user.js, chrome-extension/background.js, chrome-extension/chrome-shooter.js, chrome-extension/randomstring.js, chrome-extension/url-domain.js, chrome-extension/uuid.js, package.json, server/src/clientglue.js, server/src/ga-activation.js, server/src/views/frame.js, static/js/parent-helper.js
```sh
$ npm run lint
> pageshot@0.0.1 lint /Users/pdehaan/dev/github/mozilla-services/pageshot
> eslint .
/Users/pdehaan/dev/github/mozilla-services/pageshot/addon/lib/main.js
186:5  error  'hotKey' is defined but never used  no-unused-vars
/Users/pdehaan/dev/github/mozilla-services/pageshot/server/src/views/frame.js
1:16  error  'Raven' is defined but never used  no-unused-vars
✖ 2 problems (2 errors, 0 warnings)
```
Fixes #1195
=> Fix a few ESLint errors due to exports oddness

.sass-lint.yml, package.json, static/css/content.scss, static/css/inline-selection.scss, static/css/pageshot-notification-bar.scss, static/css/panel.scss, static/css/profile.scss, static/css/shot-index.scss, static/css/styles.scss
Ref: #1212 
Turns out you can mostly clean your Sass by converting your SCSS to SCSS using Sass' `sass-convert` tool:
```sh
$ sass-convert static/css -R -T scss -F scss -i
```
This leaves us with 24 warnings which will consider a bit more thought (or relaxing of sass-lint rules):
```sh
$ npm run sass
> pageshot@0.0.1 sass /Users/pdehaan/dev/github/mozilla-services/pageshot
> sass-lint -v -q
./static/css/inline-selection.scss
63:24  warning  Class '.pageshot-topLeft' should be written in lowercase with hyphens                      class-name-format
81:24  warning  Class '.pageshot-topRight' should be written in lowercase with hyphens                     class-name-format
107:24  warning  Class '.pageshot-bottomLeft' should be written in lowercase with hyphens …
```
=> Add sass-lint workflow

server/src/server.js
Removes the `X-Powered-By: Express` header, because would we need that.
```sh
$ curl https://pageshot.net/ -v
*   Trying 52.42.215.50...
* Connected to pageshot.net (52.42.215.50) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: pageshot.net
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET / HTTP/1.1
> Host: pageshot.net
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Security-Policy: default-src 'self'; img-src 'self' www.google-analytics.com pageshot-usercontent.net data:; script-src 'self' www.google-analytics.com 'nonce-3c6f902d-144c-4d03-993c-42d4a0fff2f8'; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; connect-src 'self' …
```
=> Remove 'X-Powered-By: Express' header

package.json
Adds [**nsp**](http://npm.im/nsp) Node Security scanner to check for known vulnerable modules and runs via "postlint" hook locally and on Travis-CI (failing the build if known issues are found).
Fixes #1601
=> Remove unused dependencies, add nsp scanner

.eslintignore, circle.yml
The server tests I hoped to add with this aren't quite ready so this just adds the basic skeleton. It runs the addon tests, starts a server and uses the existing `test-request` to make sure everything is basically ok. It's also set up to report to codecov once we have test coverage.
=> added circle.yml

webextension/background/main.js, webextension/background/takeshot.js
Open /creating page right away, and navigate to the shot page once the upload is complete
To test you have to run the local server like this:
TEST_SLOW_RESPONSE=20000 ./bin/run-server
Then it's really slow and you see the creating page.
=> Fix #2197, reintroduce the /creating page

addon/bootstrap.js
=> Add missing bootstrap.js lifecycle functions

addon/webextension/_locales/en_US/messages.json, addon/webextension/background/main.js, addon/webextension/background/senderror.js, addon/webextension/manifest.json.template, addon/webextension/selector/ui.js
Fixes part of #2294. Doesn't yet manage the transformation from a pontoon .properties file to this messages.json format.
I haven't been super consistent about the l10n keys. If anyone has strong opinions here, I am open to suggestions (cc @flodolo).
=> Extract strings using WebExtension i18n library

Makefile, docs/export-to-firefox.md
The environment variable EXPORT_MC_LOCATION provides for changing where the add-on is exported to.
=> Fixes #2318: Provides export_addon makefile rule to export pageshot into a mozilla-central based repository.

.gitignore, Makefile, addon/install.rdf.template, addon/webextension/manifest.json.template
Add browser_style to suppress a warning
=> Fix #2314, generate install.rdf from package.json version

addon/webextension/background/main.js
Fixes #2381.
This was a last-minute string change in the string extraction PR, but I missed the spot where the string is actually used.
=> Update stray l10n key

Makefile, bin/export_mc.py, bin/require.pip, docs/export-to-firefox.md
This is at least a partial fix for #2319 - it creates a branch and a commit of the exported add-on. At the moment you still need bug 1346825 applied on the default branch for this to work.
It works slightly better in git (or at least, its slightly easier to recover from) - for Mercurial it uses bookmarks, which I've found a little confusing (it creates a bookmark ok, it is getting back to 'default' and killing the commits that is the issue there).
In any case, it should be reasonably adaptable if we need to change it.
=> chore: Simplify exporting to mozilla-central by adding a script which exports and creates branches and commits.

addon/webextension/background/senderror.js
`browser.notifications.create` will throw if you pass it a `null` message, but it's fine if the message is an empty string.
Fixes the odd error message I've been seeing in the browser desktop notifications today:
Before:
After:
=> Pass empty strings, not null, to notifications API

addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js
=> Split screenshot iframe into preselection and selection iframes

addon/webextension/background/main.js, addon/webextension/manifest.json.template
It seems like disabling the pageshot button on these pages is better than doing anything else. It needs the `tabs` permission (I don't know if that's ok or not) since `activeTab` doesn't kick in until a user action is performed.
I don't know what to do about framesets yet.
closes #2236
=> disable the pageshot button on about,data,moz-extension pages

addon/webextension/background/main.js
This partially addresses @SoftVision-CosminMuntean's comment https://github.com/mozilla-services/screenshots/pull/2368#issuecomment-288721037
It'll prevent the context menu item from being added to excluded pages except the screenshots site itself by way of the default schemes in [match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns).
=> Exclude some pages from the screenshot context menu item

addon/webextension/background/analytics.js, addon/webextension/background/senderror.js
I kept getting undefined when I tried to use the `refreshTelemetryPref` promise inside `reportError` (maybe a devtools error?), so I went ahead and added a lazy updating synchronous pref checker.
=> Fix #2460, control Sentry with Telemetry pref

docs/METRICS.md
r? @johngruen and anyone else
@ianb I noticed a bunch of checkboxes are struck through.  Should I just whack those lines?
=> revise metrics.md for 54 launch

addon/webextension/selector/uicontrol.js, docs/METRICS.md
Also: Clarify when tab-load event is now emitted
Add Deprecated section to list old events we don't submit
=> Make beforeunload event match event in METRICS.md

server/src/servershot.js
A proposal for #2270
Instead of deleting the device just delete the data. (I'm not all that familiar with the server yet)
This approach doesn't require addon changes.
=> delete data instead of device on delete-all

bin/export_mc.py
I found this useful for my experiments and being able to keep the build patch at the top of the branch until we get it committed.
=> chore(export): Add an option not to base from the default branch when exporting to m-c.

static/css/inline-selection.scss
While looking at an unrelated bug, I noticed that the 'cancel' button in the selector overlay sometimes shows a flickering pointer (flickering between default and move states), and also sometimes misses clicks. Looking at the CSS, this was apparently also a problem for the download button; copying the fix over to the cancel button fixed the cancel button problems as well.
=> Fix cancel button hover problems

Makefile, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/manifest.json.template, addon/webextension/onboarding/slides.html, addon/webextension/onboarding/slides.js, addon/webextension/selector/uicontrol.js, bin/run-addon, docs/METRICS.md, locales/en-US/webextension.properties, static/css/onboarding.scss
Not complete, but working.
This will open on every browser startup if you are using `./bin/run-addon`, since the flag for whether you have seen the onboarding is reset with each run.  Hot reloading doesn't reset the flag.
Followups: #2532 #2533 
There's code duplication between slides.js and ui.js, with a FIXME to acknowledge it, but I haven't made a ticket.  It feels safer to get this complete before refactoring these.
This leaves #2307 open in anticipation of full design.
=> Start #2307, implement onboarding slideshow

Makefile, bin/update_mozbuild.py
This adds in an extra script to regenerate the Screenshots' moz.build file - basically to list all the files into the moz.build file.
We'll still need an extra script to deal with not having duplicates of the L10n files, but this is the next step along.
=> Add a script to fully list the webextension directory in moz.build when exporting, so that Windows builds are happy.

server/src/server.js
fixes #2443 
I went with 100 for the domain max length since the db field is 120 and :id uses 16 + 1. 100 is a more 'human' number than 103.
=> validate url parameters

addon/webextension/background/analytics.js, addon/webextension/background/auth.js, addon/webextension/background/communication.js, addon/webextension/background/deviceInfo.js, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/background/senderror.js, addon/webextension/background/takeshot.js, addon/webextension/catcher.js, addon/webextension/clipboard.js, addon/webextension/domainFromUrl.js, addon/webextension/makeUuid.js, addon/webextension/onboarding/slides.js, addon/webextension/randomString.js, addon/webextension/selector/callBackground.js, addon/webextension/selector/documentMetadata.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, addon/webextension/selector/util.js, addon/webextension/sitehelper.js, shared/shot.js
This seems to be working fine for me locally. The outerHTML commit is reverted, I'll work on fixing that right now.
Still unaddressed things from the big review:
- #2592 callBackground.js:
- need to see if Mark has an .eslintrc (comment at line 1), then remove the eslint globals
- look into rejecting the Promise from the parent side (comment on line 8)
- #2593 shared/shot.js: deepEqual function changes, makeUuid changes, asJson vs toJson (all kinda scary and not clear we _have_ to change them before uplift)
- #2594 background/communication.js: return a promise.resolve (line 34), don't parse error string (line 56, already an open question there)
- #2595 sitehelper.js: replace JSON.stringify with `cloneInto` (line 16, kinda seems optional IMO)
- (done) #2596 randomString.js: array indexing …
=> Webextension review changes

test/addon/head.js
This makes the test work better due to the fact the extension will be disabled in-tree via the system-disabled pref.
=> Change the mochitest to work with the system-disabled pref rather than the user facing pref.

Makefile, bin/export_mc.py
The m-c build system protects against duplicate files, so we need to avoid those. Additionally, this patch makes it
so that we don't export empty l10n files as we just fallback to en-US.
=> Fix #2642: Improve exporting files to mozilla-central, avoid duplicate/empty L10n files

addon/install.rdf.template
`hasEmbeddedWebExtension` causes the embedded web extension to be parsed when the
bootstrapped extension is installed, which triggers a race condition in
existing Firefox code during startup on a clean profile between
AddonManager and devtools code.
Removing this is not an issue for Screenshots because it delays startup
of the embedded web extension until "sessionstore-windows-restored" is
observed anyway.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1356394 for more info.
=> Remove embedded web extension in install manifest.

addon/bootstrap.js
=> Shutdown the embedded webExtension when bootstrap is asked to shutdown

addon/webextension/background/main.js
On Windows and Linux, WebExtension toolbar buttons are not
automatically dimmed when a button is disabled (bug 1204609).
This fix works for me on Windows 10.
=> Fix #2708, manually dim toolbar button when disabled

Makefile, circle.yml, package.json, test/test.js
Implement a test that invokes Screenshots, skips onboarding, clicks the Visible save button, and confirms that a new tab is opened to a shot page.
=> Fix #2695, expand Selenium test

server/db-patches/patch-15-16.sql, server/db-patches/patch-16-15.sql, server/src/dbschema.js, server/src/pages/shot/model.js, server/src/pages/shot/server.js, server/src/pages/shot/view.js, server/src/servershot.js
This adds a dmca field to the `data` table and shows a notice on the shot page when that field is not null. It could also be used for a link to specific info but is currently only used as a flag for a general message.
=> added DMCA notice to shot page

server/src/pages/shotindex/server.js
So #2737 removed the delete buttons from the thumbnails but this *woulda* fixed it, trust me 😉 
The route should still have the csrf token anyway.
=> added csrf token to /shots route

addon/webextension/background/communication.js, addon/webextension/background/senderror.js, addon/webextension/background/takeshot.js, addon/webextension/catcher.js, addon/webextension/selector/callBackground.js, addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js, server/src/server.js
This handles a bunch of issues with error reporting:
* Make catcher work even after unloadModules
* Send addon version with errors
* Work around Raven bug with fetch()
* Add popupMessage for connection failure
* Pass more information about exceptions from background to workers
* Don't cancel the shot process in the case of certain errors
=> Error handling improvements

static/css/onboarding.scss
Added a media query to scale the onboarding slides to fit a smaller window. Is this the correct approach, and does it look okay?
This is a (work in progress) fix for #2654
=> fix: Scales onboarding slides to fit smaller windows

docs/METRICS.md, server/src/server.js, server/src/servershot.js
=> extended direct-view event with ownership

bin/export_mc.py
Tried exporting to my local m-c copy with this addition to the script, and I indeed see the Sentry settings added to buildSettings.js:
```diff
diff --git a/browser/extensions/screenshots/webextension/build/buildSettings.js b/browser/extensions/screenshots/webextension/build/buildSettings.js
index 37740afd0756..6dfe230ad1a0 100644
--- a/browser/extensions/screenshots/webextension/build/buildSettings.js
+++ b/browser/extensions/screenshots/webextension/build/buildSettings.js
@@ -1,5 +1,5 @@
window.buildSettings = {
-  defaultSentryDsn: "",
+  defaultSentryDsn: "https://97d8afa496f94764ae255e739b147f4b@sentry.prod.mozaws.net/139",
logLevel: "" || "warn"
};
null;
```
=> Fixes #2782, set Sentry URL when exporting to m-c

server/src/pages/shot/controller.js
Unfortunately I couldn't reproduce the error, but there's lots of ways to configure uBlock, so I'm guessing I just didn't have it configured to block `ga-activation.js`
Still, this should protect against the reported error.
=> Fix #2790, allow JS to run even when ga-activation.js is suppressed

server/src/pages/shot/page.js, server/src/pages/shot/view.js, server/src/reactrender.js, server/src/reactruntime.js
This duplicates some of the React logic that shows the clip image when it loads, but will run even if the bundle doesn't load or there's other Javascript errors.
Incidentally fixes #2651
=> Fix #2792, make clip image.onload resilient

addon/webextension/background/takeshot.js
To reproduce #2842:
$ TEST_SLOW_RESPONSE=5000 ./bin/run-server
Then save a shot, close the /creating page, and previously you'd get an error (the shot was created, but the add-on would try to update the tab that had been closed).  With this change a new tab is opened in that case.
=> Fix #2842, if the /creating tab is closed open a new tab instead of updating the nonexistent tab

server/src/config.js, server/src/server.js
I don't know if this will actually fix our problems, but from everything I can tell it should.  `req.protocol` is a getter, but its [logic is fairly simple](https://github.com/expressjs/express/blob/c087a45b9cc3eb69c777e260ee880758b6e03a40/lib/request.js#L306-L320).  `trust` is created [here](https://github.com/expressjs/express/blob/c087a45b9cc3eb69c777e260ee880758b6e03a40/lib/utils.js#L232-L251) with a `val` of `true`. 
Once applied we need to update our environmental config.
=> Fix #2734, make protocol configurable with EXPECT_PROTOCOL=https

addon/webextension/buildSettings.js.template, addon/webextension/selector/shooter.js
Text capture can be enabled by setting the SCREENSHOTS_CAPTURE_TEXT env
var to 'true'.
With the env var set:
Without the env var set:
=> Fix #2931: disable DOM text capture by default

addon/webextension/background/senderror.js, bin/export_mc.py, bin/release-version
This changes the DSNs to the private DSNs in new Sentry projects
Discussion of using a private DSN in https://bugzilla.mozilla.org/show_bug.cgi?id=1369162
WebExtension background pages do not have a referrer or origin on their requests, therefore we need authenticated endpoints
=> Fix #2920, fix sending errors to Sentry

server/src/config.js, server/src/server.js
This adds a new configuration, EXTRA_CONTENT_ORIGIN, which is added to the CSP
This is intended just for migrating the pageshot.net content origin
=> Fix #2933, allow for EXTRA_CONTENT_ORIGIN

bin/export_mc.py
Add --no-commit option, so you can preview the changes without causing a commit
Validate --branch or --no-switch-branch options
Make it valid Python 3 (and Python 2), even though we aren't using Python 3, because my editor for unrelated reasons is now linting everything as Python 3.
=> Implement some small improvements to export_mc

addon/webextension/manifest.json.template, test/test.js
IIRC we decided not to localize the button label, but I hard-coded the string "Firefox Screenshots" in background/main, yet also localized it in the manifest (probably in a flurry of l10n edits).
Ian mentioned the browser test was inconsistent about the button label text; this is certainly why.
Browser test updated, seems to work consistently for me locally.
=> Consistent button label

addon/webextension/background/senderror.js, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, docs/error-handling.md, locales/en-US/webextension.properties, server/src/servershot.js, shared/shot.js
This deals with several issues from #2957:
* Log weird data URLs better
* Fix the Save button staying stuck disabled
* Fix changing the clip after an unsuccessful save
* Give an error when you have zero-area selection
=> Save resilience

CONTRIBUTORS.md
Add Rob Helmer. CONTRIBUTORS should be up-to-date up to this commit
=> Add localizers to CONTRIBUTORS

addon/webextension/README.md, addon/webextension/background/README.md, addon/webextension/background/communication.js, addon/webextension/background/main.js, addon/webextension/background/startBackground.js, addon/webextension/manifest.json.template
This takes a minimal approach, loading scripts using the script tag on the first button click.
Also creates and intercepts the contextMenu action, and any incoming communication
Reads onboarding flag and changes icon as necessary
Close reading of this would be welcome! It's a pretty substantial change, more than the lines of code would imply.
=> Fix #2843, lazily load code into the background page

addon/webextension/selector/ui.js
This can happen after the worker has been torn down, and this.save isn't defined
=> Guard access of this.save when un-disabling the save button

locales/en-US/webextension.properties
Turns out `termsAndPrivacyNotice` was the original name of this string, so opted to increment a counter at the end :-P
=> Fix #3024, update terms and privacy language

addon/webextension/selector/callBackground.js
This happened in some weird corner case while debugging
=> Protect against an empty response

addon/bootstrap.js
This reverts the previous startup cache attempt.  It addresses changes useful when https://bugzilla.mozilla.org/show_bug.cgi?id=1372750 lands, and also requires https://bugzilla.mozilla.org/show_bug.cgi?id=1373749
In a landing patch we'll change the cache schema version to fix #3027 
The [v10-release](https://github.com/mozilla-services/screenshots/tree/v10-release) branch contains these changes and a version bump to 10.3.0.
=> New startupcache approach

static/css/frame.scss
See #2516 for details. This seems to not break anything and fix the IE bug. Note that modern.ie does still exist, for verifying the fix.
=> Fix #2516; Tweak flex syntax so shot pages work on IE 11

.npmrc
See https://github.com/mapbox/node-pre-gyp/issues/298 for details.
=> Disallow package-lock for npm5 fsevents compatibility

addon/install.rdf.template
Changed the homepage from pageshot.net to https://screenshots.firefox.com.
=> Fix #3041, Changed homepage value

shared/shot.js
This adds : (important on Windows), \, <, and > to the blacklist.
Followup in #3083
=> Fix #2981, sanitize download filename more fully

addon/bootstrap.js
In test conditions, when the browser is started and stopped very quickly, sometimes we didn't shut down the WebExtension because it hadn't fully started.
r=kmag (in https://bugzilla.mozilla.org/show_bug.cgi?id=1373614)
=> Fix Bug 1373614, stop the embedded WebExtension unconditionally

addon/webextension/selector/uicontrol.js, test/test.js
The tests expected that a click on .visible would immediately upload the screenshot. This patch changes it to click the save button before expecting upload.
=> Fix #3039, update tests for full-page preview

Dockerfile
@relud Maybe this is why the locales are missing from dev right now?
The server code in /server/src/l10n.js looks for the locales at "../../locales", which I think corresponds to the one-liner added to the Dockerfile.
Not sure how to test this, as I haven't gotten the Docker image working locally.
=> Add locales to Docker app

locales/en-US/server.ftl
The fluent serializers sadly don't deal gracefully with the full fluent syntax spec.
While @stasm is on vacation, let's make the server.ftl conform with the support subset.
I haven't found a better way than running the file through tools/fluentfmt.py in python-fluent, and even that only works with a local edit to serialize to utf-8.
@mathjazz, can we test this on stage in some sort?
=> L20n syntax subset

locales/en-US/server.ftl
Either is missing a "button", or it should not have a "the" before. Since there are already two "button" in the string, I opted for removing "the".
=> Fix homePageCapturePageDescription for en-US

test/addon/browser_screenshots_ui_check.js
Currently, when exporting the addon to Firefox, an upstream refactoring (from generator functions to async/await syntax) gets reversed. Fixing this in master will reduce the number of potential export gotchas by one. (Maybe this should be landed in the export branch instead, for now?)
=> Fix #2917, update browser test to match refactoring in mozilla-central

server/src/pages/shotindex/view.js
It was previously sending the origin of the original shot, while it should have been sending the URL of the screenshot image
=> Fix #3155, make the Pinterest share work from the index page

server/src/pages/shot/view.js
With site metadata hidden there is much more room for the editing widget and explanation string
=> Fix #3178, hide site metadata when editing the expiration

addon/webextension/selector/ui.js
Fixes #2459 
Setting the width of the background highlight divs to a 100% seems to fix the problem.
=> sets background highlight width to 100%

server/src/server.js
In retrospect we don't ever need to do bucket creation, so this just removes it
=> Fix #3111, don't create S3 bucket on server startup

server/src/pages/shot/view.js
Fixes #3201 
Looks like the issue was with the column-space class. Moving the promo bar out of the flow seems to have fixed the problem (tested on chrome and safari).
=> remove extra space under firefox promo bar

addon/bootstrap.js, addon/webextension/background/main.js, addon/webextension/background/startBackground.js, addon/webextension/manifest.json.template, test/addon/browser_screenshots_ui_check.js, test/addon/head.js, test/test.js
This removes the browser action and adds a Photon page action,
pursuant to https://bugzilla.mozilla.org/show_bug.cgi?id=1366041.
Right now Photon page actions are unrelated to WebExtension page
actions unfortunately, which means that this patch has to do most
of its work in bootstrap.js.  The WebExtension part passes
messages to bootstrap.js to handle clicks and update the action's
title and icon as necessary.
=> Replace the WebExtension browser action with a Photon page action.

server/src/pages/shot/view.js
=> Fix #3271, insert a space between sentences in Get Firefox CTA

server/src/pages/shot/page.js, server/src/pages/shot/view.js
TL;DR: moves shot image to a plain old image tag, making the shot page functional in IE, Edge, and any browser with JS disabled.
The shot image wasn't loading in Edge or IE (#2935) because those browsers don't support the CSP nonce directive. (The very latest version of Edge, released this week with the Windows 10 Creators Update, does support CSP level 2.) I'm not sure why the regular image loading detection code failed, but the CSP error explains why the inline fallback code failed.
This seemed like a good opportunity to get rid of the code that hides the image until it's loaded. Simplifies the code and makes the pages accessible without JS.
I set the spinner as a centered background image of the image tag itself; it's weird-looking now, but once jgruen replaces the svg with a simple …
=> Load shot image directly

addon/webextension/onboarding/slides.html, addon/webextension/selector/ui.js, static/css/onboarding.scss
Fixes #3273
This fully merges both the v10.4.0-export and v10.10.0 branches into master. The full screen commit gets merged and committed.
=> Merge v10.10

locales/en-US/server.ftl, server/src/pages/leave-screenshots/model.js
The "Remove Page Shot data" page was wrongly titled as "Confirm account deletion" 
I changed it to "Remove All Data".
=> Fix #2140 "Remove Page Shot data" page is wrongly titled as "Confirm account deletion" 

static/css/partials/_share-panel.scss
Fixes #2873.
@johngruen R? Kinda brittle selector, but works
=> Correctly position share panel on non-Firefox browsers

circle.yml, test/test.js
Also the label changed for unknown (but presumably unimportant) reasons
=> Fix #3306, make tests resilient to a browserAction or pageAction

bin/run-addon
Unfortunately while Screenshots loads up with this patch (instead of being disabled), it doesn't work in Nightly due to regressions.
=> Fix #3333, make run-addon work with new legacy pref

server/src/servershot.js
Fix for [Bug 1389706](https://bugzilla.mozilla.org/show_bug.cgi?id=1389706)
=> empty docTitle value in JSON data

server/src/middleware/l10n.js, server/src/server.js, test/server/unit/middleware/l10n-test.js
(Thought I had goofed up the header mocking in the previous PR, but it seems correct.)
Deliberately making the unit test additions as small as possible here, while still providing diagnostic value.
Open question: should we change npm test to npm-run-all test:*?
=> Set language default correctly, add server unit tests

server/src/pages/shotindex/server.js, server/src/servershot.js
Looking at the DB queries that generate the My Shots page, the query that [gets all devices for the current user](https://github.com/mozilla-services/screenshots/blob/6608d2e3f229c5fb986ddba557dab1bfe1711bca/server/src/servershot.js#L467-L471) seems problematic, based on the EXPLAIN output (note the Seq Scan):
```
jhirsch=# EXPLAIN ANALYZE SELECT DISTINCT devices.id FROM devices, devices AS devices2 WHERE devices.id = 'anoneb12496a-e845-4f09-8fa6-0e877b7d4438' OR (devices.accountid = devices2.accountid AND devices2.id = 'anoneb12496a-e845-4f09-8fa6-0e877b7d4438');
Unique  (cost=22395.73..22407.76 rows=2405 width=33) (actual time=40.324..40.768 rows=1 loops=1)
->  Sort  (cost=22395.73..22401.75 rows=2405 width=33) (actual time=40.324..40.511 rows=2420 loops=1)
Sort Key: devices.id
Sort …
```
=> Simplify retrieval of My Shots data, hopefully speeding things up

server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, test/server/clientlib.py, test/server/test_responses.py
Adds smoke tests for more routes and fixes a 500 error loading my shots from an unauthed page with no shots.
I can rebase this if the changes in clientlib might conflict with #3417
r? @ianb
=> Server test responses

static/css/inline-selection.scss
Changes:-
1. Shifted all three buttons (cancel,download,save) from right to left
2. Swapped the position of text and image on save button
=> Fix #3241 : Moved buttons from right to left 

addon/webextension/clipboard.js
This logs cases when the passed-in text is empty, or the textarea select doesn't appear to work. Logs are sent to Sentry.
=> Fix #3406, add logging of unexpected clipboard state

bin/build-scripts/bundle_dependencies, package.json
This always builds bundles as a production build. envify and uglifyify should also help improve overall bundle sizes
=> Fix #2254, build production versions of bundles

circle.yml
codecov already tracks coverage
=> server: skip extra code coverage in CI

server/src/pages/shotindex/controller.js
If user isn't authed, reload once, then bounce to homepage
=> Fix #2939, avoid infinite refresh loop on shots page

server/src/middleware/csrf.js, server/src/pages/leave-screenshots/server.js, server/src/pages/settings/server.js, server/src/pages/shot/server.js, server/src/pages/shotindex/server.js, server/src/server.js, test/server/clientlib.py, test/server/test_csrf.py
Rebased and slightly updated version of https://github.com/mozilla-services/screenshots/pull/3353
Rolling back the cookie key to the default of `_csrf` might have fixed https://github.com/mozilla-services/screenshots/pull/3353#issuecomment-325711537 for now.
Quickly ran some simple functional tests: reload the webextension, take a shot, edit it, change expiration, change title, delete it, delete account.
Didn't verify that the secure attr was set but hopefully that's OK to test in dev or stage.
=> 3299 header tweaks take 2

bin/build-scripts/bundle_dependencies
Fail on stuff like: https://github.com/mozilla-services/screenshots/pull/3440#issuecomment-326625163
I don't think this covers: https://github.com/mozilla-services/screenshots/pull/3458
=> fail server build for imports out of build/ and node_modules/

bin/load_test_exercise.py, server/src/server.js, server/src/users.js, test/server/clientlib.py, test/server/test_auth.py
refs: 3. of bug 1389708
Validate deviceIds are uuids.
This assumes there aren't any versions of the extension registering with a different format or if there are it's OK to break them.
r? @ianb
=> validate deviceId in /api/register

server/src/pages/leave-screenshots/server.js, test/server/test_csrf.py
The csrf cookie shouldn't outlive the session and since we're using signed cookies we need to expire the cookie manually.
=> clear csrf cookie on successful leave

addon/bootstrap.js, addon/install.rdf.template, addon/webextension/background/README.md, addon/webextension/background/main.js, addon/webextension/background/startBackground.js, addon/webextension/manifest.json.template, test/addon/browser_screenshots_ui_check.js, test/addon/head.js
This changes the add-on to require the Photon page action, with no fallback to a browserAction
- Removes test for Photon (assumes it is present)
- Removes bootstrap.js code that deletes the browserAction button
- Removes webextension code references to browserAction
- Removes Photon conditionals (i.e., assume it's always Photon)
- Make 57a1 the minimum version for the webextension/install.rdf
=> Fix #3468, remove browserAction

docs/running-mochitests.md
I was just poking around and found a link needing fixing 🎩
=> fix broken "Export to Firefox" link

server/src/pages/shotindex/controller.js
This lets a user who accesses Screenshots from the Library, but has never authenticated or used Screenshots, get redirected to an onboarding tour.
Also sends non-57 users to the normal onboarding without UITour
=> Fix #3493, send unauth'd /shots to /#tour

server/src/middleware/csrf.js, server/src/pages/leave-screenshots/server.js, server/src/pages/settings/server.js, server/src/pages/shot/server.js, server/src/pages/shotindex/server.js, server/src/server.js
Changes:
* Default to using csrf middleware for all routes
* Remove route specific csrf middleware
* combine csrf and csrfProtection middleware
If new routes need to skip csrf protection for some reason we can add their URI paths to `isCsrfExemptPath` in middleware/csrf.
r? @6a68
=> Csrf refactor

circle.yml, test/server/test_file_management.py
The tests are too slow to run in any normal process, so this will keep developers from getting caught up in them.
=> Use pytest.mark to suppress the test_file_management tests

.nsprc
I got my branches a little off so there's some spurious commits, but I guess merging this will make it right again? Followup in #3532
The security issue is a Denial Of Service opportunity with tough-cookie and certain very large headers. It's possible that we already have long header blocking somewhere in our stack.
=> Fix nsp error

bin/build-scripts/write_build_time.py
Works for me locally; note the 'After' commit points to the commit in this PR.
Before:
```json
{
"source": "https://github.com/mozilla-services/screenshots/",
"description": "Firefox Screenshots application server",
"version": "20.0.0",
"buildDate": "September 21, 2017 17:39:13 UTC",
"commit": "8.1.0-1574-gc21f3d38",
"contentOrigin": "localhost:10080",
"commitLog": "https://github.com/mozilla-services/screenshots/commits/8.1.0-1574-gc21f3d38",
"unincludedCommits": "https://github.com/mozilla-services/screenshots/compare/8.1.0-1574-gc21f3d38...master",
"dbSchemaVersion": 20
}
```
After:
```json
{
"source": "https://github.com/mozilla-services/screenshots/",
"description": "Firefox Screenshots application server",
"version": "20.0.0",
"buildDate": "September 21, 2017 18:14:38 UTC", …
```
=> Use correct latest commit in __version__ endpoint

addon/webextension/background/startBackground.js
bootstrap.js sends the tab ID with the Photon page action, but it doesn't have the complete set of information that the WebExtension tab object has
=> Fix #3491, stop Screenshots in Private Browsing

addon/webextension/selector/shooter.js
The clip object is used to inform the download filename, so we need to add a clip before generating the filename
=> Bug fix for #3513, create proper extension for downloads

addon/webextension/blobConverters.js, addon/webextension/selector/shooter.js
This only covers cases in the JPEG commits, to keep the resulting diff minimal
=> Put limits on uses of string.split

addon/webextension/selector/ui.js, static/css/inline-selection.scss
For whatever reason, separating out the opacity bit from the background color partially resolved the problems with the selector interface. Props to MattN for suggesting this workaround.
Unfortunately, something about how the `.hover-highlight` layers translucent white on top of translucent black causes it to remain fully opaque. The click-and-drag selection works fine. Turns out that background images aren't displayed on High Contrast mode on Windows, so we could use a tiled background image for the `hover-highlight`. Another, more complex hack, would be to set a dummy background image (`background-image: url('#')` suggested [on SO](https://stackoverflow.com/questions/16213395/windows-7-high-contrast-theme-overrides-website-colors-in-firefox)), check if the background-image property is …
=> Fix #3174, make selector view usable on high contrast themes

addon/webextension/buildSettings.js.template, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, locales/en-US/webextension.properties, shared/shot.js, static/css/inline-selection.scss
Adds a new captureType, fullPageTruncated
Looks like this:
=> Fix #2129, notify user when full page is cut off

shared/shot.js
This patch removes all control characters (0x00...0x1F) from filenames, not only "\n\r\t".
They are not allowed in Microsoft Windows file names, see:
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#naming_conventions
And possibly in other systems:
https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words
=> Fix: remove control characters from filenames

addon/webextension/selector/ui.js, static/css/inline-selection.scss
Sadly, the `-ms-high-contrast` media query isn't supported in Firefox. Firefox doesn't render background images in high contrast mode; use this latter fact to detect high contrast mode.
High contrast mode isn't needed for the preview frame, because it makes the full page shot weirdly transparent.
=> Better hcm detection

server/src/caching.js
This is relatively safe since we use commit-hash-based cache busters on URLs.
This fixes one of the last issues from #3202
=> Extend default resource expiration time to 30 days

package.json, test/server/unit/l10n-test.js, test/server/unit/middleware/l10n-test.js
Note tests have broken when they weren't being run.
I'm not that clear on how the tests *should* act, so I'm not sure how to fix. Errors:
```
1) l10n middleware getLanguage function (Accept-Language header parsing) should return ["en-US"] if Accept-Language header value is "en-CA":
AssertionError: 'en-US' == 'en-CA'
+ expected - actual
-en-US
+en-CA
at Context.it (test/server/unit/middleware/l10n-test.js:24:14)
2) l10n middleware getLanguage function (Accept-Language header parsing) should return ["en-US"] if Accept-Language header value is "en":
AssertionError: 'en-US' == 'en'
+ expected - actual
-en-US
+en
at Context.it (test/server/unit/middleware/l10n-test.js:30:14)
```
=> Fix #3372, run server unit tests with npm run test

.nsprc
As seen in [1], we had to temporarily disable nsp checks due to a
potential vulnerability in tough-cookie. The request library has been
updated to use the updated tough-cookie, and, thanks to loose version
tracking, looks like the fix percolates up to all our deps.
[1] https://circleci.com/gh/mozilla-services/screenshots/3561
=> Fix #3532, remove .nsprc file now that tough-cookie has been updated

server/src/pages/shot/time-diff.js
The Localized fluent-react component doesn't coerce strings to numbers,
so strings like "1" are mistakenly rendered using the default
pluralization. Bug #3495 is due to our use of the plural as the default
(for example, see the 'timeDiffMinutesAgo' l10n key).
=> Fix #3495, Fix pluralization by passing integer time diffs as numbers, not strings

addon/webextension/background/auth.js, addon/webextension/sitehelper.js, server/src/middleware/csrf.js, server/src/server.js, test/server/clientlib.py, test/server/test_auth.py
This adds a second attempt to login to wantsauth logins, one that runs in sitehelper.js, and tries to get the cookie set on a request that appears to come from the content page itself.
Note: this now works, but doesn't provide full protection from a screenshots.firefox.com page (that is under attack) from getting the authentication header.
=> Try to fix #3581, make Screenshots work with third party cookies disabled

addon/webextension/selector/uicontrol.js
Source code files on dxr.mozilla.org are rendered as floats inside a
non-clearfixed parent element, which has a calculated height of 0. This
condition isn't handled in the current loop logic, leading to an infinite
while loop that locks up the UI.
=> Fix #3314, Avoid infinite selection loop by checking minimum size

server/src/caching.js, server/src/server.js
Without data, I'm taking a guess that shot access/share has a long tail, so the cache expiration is set to a day.
Fix #3591
=> Set cache expiration for shot images. (#3591)

circle.yml
The zap baseline 2 branch was deleted so https://raw.githubusercontent.com/mozilla-services/screenshots/zap-baseline-2/.zap-baseline.conf 404s.
refs: https://github.com/mozilla-services/screenshots/pull/3321
r? @6a68
=> Update circle.yml change baseline conf to master

CHANGELOG.md, README.md
This includes all the latest commits (under no version) so that they won't get lost the next time ./bin/generate-commit-log recent is called
The diff looks kind of crazy because I moved stuff around, but sometimes the diff algorithm thinks I moved everything out of the way of the one chunk I actually moved.
=> Fix #3624, separate out 19.1.0 and 19.2.0 in changelog

test/addon/head.js
Landed in m-c as https://hg.mozilla.org/mozilla-central/rev/d15f945998db,
but didn't backport this change to github master.
=> Remove system-disabled pref from addon test

.gitignore, addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js, addon/webextension/selector/ui.js, locales/en-US/webextension.properties, static/css/inline-selection.scss
@youwenliang @johngruen Mind taking a look?
Updated, now showing the download-only mode warning in the full-page preview; see screenshot below.
~~Nearly done, but just realized I've got to add the warning to the full-page preview frame. Need to do a round of todo cleanups, too.~~
Screenshots of the private browsing mode screens:
=> Download only mode

addon/webextension/selector/ui.js
Not much else to add. Testing: open a private browsing window, scroll an infinite scroll page till it's taller than 5k pixels, click the full page button, check the notice shown at the bottom of the screen is just the download-only notice
=> disable full-page truncation warning if download-only warning will be shown

addon/bootstrap.js, addon/webextension/background/main.js, addon/webextension/background/takeshot.js
For related, Gecko-only changes to the telemetry Scalars.yaml file, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1412411
=> Fix #2218, add Telemetry scalars to track shot creation per session

server/src/ab-tests.js, test/test-ab-test.js
This separates out people who are excluded from a test, from those who are in the control for the test. 50% of people always go to control, and 50% go into some experiment branch. People who aren't in either go into the 'exclude' category.
=> Fix #3674, put 50% of people into control

static/css/shot-index.scss
Removed the `display: block;` on `<a>` that was causing the problem.  Also simplified the css a bit.
Fix #3715
=> Fix (and simplify) pagination related css.

addon/webextension/selector/ui.js
The `unhide()` being deleted was called before the iframe's loaded, which is causing #3692.  But because the `usePreselection` call at https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/selector/uicontrol.js#L410 triggers an `unhide()`, this `unhide` call is unnecessary.
Fix #3692
=> Remove extra preselection frame unhide() 

shared/shot.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=366192
=> Bug 366192 [bugzilla.mozilla.org] - Fixed http/https regex checks.

addon/bootstrap.js
Bug 1395387 changed the Photon page action API so that `title`
and `iconURL` are no longer properties but methods, setTitle()
and setIconURL().  We need to update our consumer.  Right now,
setting these properties isn't doing anything at all.
=> Properly set the Photon page action's title and icon.

addon/webextension/selector/ui.js
=> Stop using window.inner[Width|Height] because of scroll bars.

shared/shot.js
The regex was meant to match '-', but the dash was treated as a range
=> Fix bug in shot id regular expression

server/src/share-buttons.js
This gets fired from the Shot page (the property is defined on the Shot Index page)
=> Fix a bug where this.props.setPanelState is not defined

server/src/pages/homepage/controller.js
The UITour-lib.js library is loaded async, and the homepage-bundle can potentially load and run before it (we saw this in Sentry). This puts in a 1 second retry when that happens.
=> Fix bug when UITour-lib.js loads after homepage-bundle.js

addon/webextension/background/analytics.js, addon/webextension/background/takeshot.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, docs/METRICS.md, server/src/middleware/csrf.js, server/src/server.js
The metrics docs changes cover the basic overview.
The iframe unhide events seem to fire slightly before the UI is updated, but given how horrifyingly slow some of the steps are (especially full-page previews & downloads), I suspect these start and end points will be good enough for a while.
Easiest way to test this is to filter on 'perf' in the browser console, then run through various shot creation + download/upload flows:
=> Fix #3673, instrument response times in shot creation flow

addon/webextension/selector/ui.js, static/css/inline-selection.scss
=> Update css class name to restore download-only tooltip.

addon/webextension/domainFromUrl.js, shared/shot.js, static/js/wantsauth.js
This is a followup to 2bd42beed9f18f626e328fa73f2dd6fd8be57e6f that applies the same fix to other regular expressions
=> Fix remaining domain regexes

addon/webextension/background/main.js, addon/webextension/icons/copy.svg, addon/webextension/selector/shooter.js, addon/webextension/selector/ui.js, addon/webextension/selector/uicontrol.js, locales/en-US/webextension.properties, static/css/inline-selection.scss
=> Copy image to clipboard

addon/bootstrap.js, addon/webextension/background/main.js
While reviewing the export patch for version 25, I realized we aren't incrementing the Telemetry counter when shots are copied.
=> Track the number of copied shots in Telemetry

addon/webextension/background/analytics.js
Don't throw a user-visible error if anything goes wrong with sending data to the `/timing` endpoint
=> Silence any timing-related errors

addon/webextension/selector/ui.js
Inlining the `.replace('"', "&quot;")` over and over just looked too ugly.
Would really be nice to extend the `data-l10n-id` processor to handle,
say, `data-l10n-title` for this case, but aiming for the quick fix.
=> Fix #3815, escape quotes in localized attributes

bin/update_mozbuild.py
This seems to be a new ./mach build requirement
=> Fix #3826, sort all file lists in moz.build

server/src/pages/shotindex/controller.js
=> Handle the boundary case where the user deletes the last shot of a page

Makefile, addon/webextension/background/startBackground.js, addon/webextension/background/takeshot.js, docs/testing-the-api.md, server/src/pages/shot/controller.js, server/src/pages/shotindex/view.js, server/src/server.js, server/src/servershot.js, shared/shot.js, shared/thumbnailGenerator.js
- The thumbnails are generated on the browser.
- The thumbnails are scaled and cropped in the same fashion as how My Shots display shots as thumbnails currently; they are not simply scaled down copies of the shot image.
- The thumbnails are always PNGs.
- This patch piggyback on some existing thumbnail related code (that did not seem to be in use?).  That code inserts the thumbnails into the `images` table and allows the thumbnails to be managed identically to the shot images.
- My Shot will fall back to using the full size shot image if a thumbnail isn't available.
Fix #3282
=> Generate, upload, and display thumbnail of shots.

addon/webextension/background/analytics.js, server/src/server.js
Fix #3757 
This uses `window.requestIdleCallback`.  For the current user timings, it makes no difference because those are relatively far apart.  If the user actions are quick enough, some batching occurs with event tracking.  Of course, the slower/busier the computer, the more batching potential.  Everyone's Mileage May Vary.
The server side of this patch is backwards compatible with older clients.
=> Batch event and timing analytics data.

addon/webextension/sitehelper.js, locales/en-US/server.ftl, server/src/pages/shot/view.js, server/src/server.js, static/css/frame.scss, static/js/wantsauth.js
This adds backupCookieRequest to the sitehelper login process, to tell the site if third party cookies SHOULD work. If the site sees that third party cookies might not be enabled, then it does a second check to GET /api/check-login-cookie. If that request shows the cookie isn't set, then it changes the model to warn the user.
TODO:
- NOT DONE set something on My Shots too (note: skipped)
- DONE write a proper LoginFailedWarning language/design
- DONE remove the changes that disable third party cookie support (it's disabled to make this easier to test)
=> Fix #3600, warn about failed login due to third party cookies

docs/export-to-firefox.md
Per jmaher and ryanvm in #perf this morning, PGO builds are used for Talos testing of beta, but not on osx. Updating docs accordingly.
=> Update Talos testing instructions for Beta

package.json, pytest.ini, test/server/test_file_management.py
Add a marker for slow tests. And skip test_file_managements.py with that marker.
Closes #3421
=> Skip test_file_managemnt tests by default

addon/webextension/selector/ui.js
=> Fix selection frame's position when content document's body's (left, top) is not at (0, 0).

addon/webextension/selector/uicontrol.js
=> Clear cached highlighted element when hiding hover box.

addon/webextension/selector/uicontrol.js
Fixes #3968 
Fixes a bug introduced by previous patch for #3968.  Variable scopes, man. 😩
=> Check capture type before it's potentially changed

shared/shot.js
=> Do not throw error on unexpected model attr in production

addon/webextension/background/main.js, addon/webextension/onboarding/slides.js
[Bug 1357589](https://bugzil.la/1357589) has been fixed, so the links should now behave normally.
Refs #2699.
=> Remove special click handlers for onboarding legal and terms links

addon/webextension/selector/ui.js
The only attribute we localize is the title attribute, so just add a selector to the `querySelectorAll` call. Additionally, inline the `getAttributeText` function, which was only used to sanitize title strings.
Fixes #3840.
=> Use data-l10n-title to localize title attributes

addon/webextension/background/analytics.js, addon/webextension/selector/uicontrol.js
Cancel some user timing measurements when page visibility changes to 'hidden'. Fixes #4055.
JS background budgeting in Firefox 58 might cause Screenshots execution to slow down if the user switches tabs while waiting for the UI to update. Exclude cases where the user timing event ends with an upload, since the result of a successful upload is to switch tabs (to the shot page of the uploaded shot).
=> Cancel user timings when the window becomes hidden

addon/webextension/background/analytics.js
With the move to batched pings, the optional second argument to `watchPromise` was dropped, causing haywire errors if users did anything with Screenshots while the network is unreachable. This patch restores that second argument, preventing analytics-related network errors from being shown to users.
=> Suppress errors encountered when sending timing or events pings

package.json
Please update the `fluent` dependency to 0.4.3.  It has important fixes to the FTL parser.
While the main development of `fluent` continues with the recent 0.6.x versions, I also published 0.4.3 which is API-compatible with other 0.4.x versions. The upgrade should be painless.
`fluent` 0.4.3 supports the recent changes to the Fluent Syntax. It also supports the syntax Screenshots and Pontoon use right now. We expect Pontoon to upgrade their Fluent dependencies early next week, at which point all translations saved back to GitHub will be serialized using the new syntax. This PR will minimize the risk of regressions from that update (which is already low because the changes to the syntax are small).
Some of the syntax changes will require an update to the en-US reference file in this repo, …
=> Update to fluent 0.4.3

addon/webextension/background/analytics.js
System clock changes during an interaction could skew the results significantly.
Fixes #4054.
=> Use Performance.now for interaction timings

test/test.js
=> Add navigate to My Shots test.

server/src/servershot.js
Add a couple of empty result checks. The APIs in server.js expect a null result if records weren't found.
This doesn't change user-facing behavior: if the shot is gone, then you try to set expiration or delete it, an error alert is shown. I guess this will avoid errors getting sent to sentry, though.
Verifying this works: create a shot, open shot page in two tabs. Delete the shot from tab 1, then try to set expiration and delete the shot from tab 2.
=> Fix #3776 - Ensure DB returned rows before trying to access them

Dockerfile, package.json
@oremj I'm not running Docker locally. Do you know of any issues to worry about with bumping our Docker base image from node:7 to node:8, maybe bugs other services have run into?
Also, I'm guilty of skipping the eslint-related changes @pdehaan suggested in #3642...we can add those to a separate good-first-bug for node linting, maybe?
=> Fix #3642, Require node 8 for docker and in package.json

test/test.js
Fixes #4108, maybe?
Since the issue is intermittent and occurs only on CircleCI, it's difficult to say with some degree of certainty that this fixes #4108 (even if the tests have passed in five builds for #4114 on CircleCI).
=> Wait until save button is visible in a test 🤷‍♂️ 

addon/webextension/selector/shooter.js, addon/webextension/selector/uicontrol.js
Fixes #4174. Changes:
* don't overwrite correctly-scaled canvas dimensions
* pass the shot type to `downloadShot` and `copyShot`
@chenba Mind taking a look? I git bisected the bug back to commit 6fa7f3a8a, but I may not have all the context around the reasons for the changes in that commit. In particular, I'm curious if "fullPage" was hard-coded for any particular reason.
=> Fix DPI scaling in download/copy 

server/src/server.js
Part of #3980 and #3979 
This patch move a few things around in the server so that most[0] of the non-document responses won't include the CSP and X-Frame-Options headers.
[0] The JSON response for the My Shots pagination data will still have those headers.
=> Stop sending CSP and frame options headers on non-documents. (#3980)

.env.dev, Dockerfile, package.json, server/src/pages/shot/time-diff.js, server/src/pages/shot/view.js
Fixes #2216 
Because default node build only supports en-US, we need to either build node with --full-icu or provide ICU data at runtime; this patch does the latter.
=> Pass in locale for date.toLocaleString.

test/test.js
Disable three tests that are failing because of changes in Firefox.  (See #4240)
=> Disable three tests temporarily.

Dockerfile, circle.yml
Fixes #2216's deployment issue
=> Match CircleCI node version to the Docker image's.

addon/webextension/background/main.js, addon/webextension/background/selectorLoader.js
=> Wait for onboarding status.

.env.dev, bin/build-scripts/bundle_dependencies
=> Do not uglify when NO_UGLIFY is set.

test/test.js
=> Add test for upload-disabled pref

package.json, server/src/helpers.js, server/src/users.js
*Edited: this PR is now a complete fix for #3681.*
Partial fix for #3681. The implementation of the `request` and `readBody` methods inside `helpers.js` assumed that the wrapped `wreck` methods were callback-based, but those methods actually return promises, so the promise chain wasn't terminated properly. I don't see any need for the helpers, so just invoked the `wreck` methods directly.
@niharikak101 Does this unblock you with fxa debugging?
Without this patch, when I do the fxa login flow on localhost, it hangs forever after entering the password and confirmation code. (When I do the same on the dev server, as in the STR for #3681, I see a 504 Gateway Timeout after a 60 second wait, which I think is nginx timing out the connection.)
With this patch, when I do the fxa login flow on …
=> Fix last step in fxa oauth flow

.env.dev, Dockerfile, package.json, server/src/pages/shot/time-diff.js, server/src/pages/shot/view.js
Fixes #4288 
With this patch, we simply don't render anything for the datetime in the title attribute on the server side.  That also means we can back out the changes made for #2216 (which is a majority of the patch). 🤘
=> Render shot capture time only when in browser

server/src/server.js
Fixes #3769, requires #4321 as it uses a fairly new option in Raven.
Hold until #4321 is merged.
=> Mask the shot url in the Raven payload.

addon/bootstrap.js
The commit https://hg.mozilla.org/mozilla-central/diff/3182593eb59a/browser/base/content/utilityOverlay.js regressed this, requiring a principal for calls to openUILinkIn(). This changes that to the function openWebLinkIn() that provides a null principal.
Note the relevant commit was by @jonathanKingston (r=@gijsk), but since he's not in this project I can't explicitly ask him for a review (though I'd take his review too ;)
I chose `openWebLinkIn()` instead of `openTrustedLinkIn()`, because a lower permission principal seemed safer.
=> Fix #4338, fix regression in Library link

addon/webextension/selector/ui.js
Landing in the Chrome branch. (I'll open a separate discussion-only PR to get feedback on the prototype overall.)
Steps to test:
- check out this branch
- `SCREENSHOTS_CHROME_BUILD=true make chrome`
- start chrome, go to `chrome://extensions`, click 'LOAD UNPACKED' in the header, choose the `webextension` directory
- load a website, right-click and choose 'take a screenshot'
- you should see the 'save visible', but not the 'save full page', button in the top-right corner of the preselection iframe:
=> Fix #4299: hide the full page button in Chrome mode

server/src/pages/shot/editor.js
=> Stop oversampling for HiDPI in annotations editor for full page shots.

locales/en-US/server.ftl, server/src/delete-shot-button.js, server/src/pages/shot/view.js, server/src/pages/shotindex/view.js, static/css/frame.scss, static/css/partials/_buttons.scss, static/css/partials/_delete-confirmation.scss, static/css/shot-index.scss
=> Update delete shot confirmation dialog.

locales/en-CA/server.ftl, locales/en-CA/webextension.properties
We are starting to distribute en-CA localization, and using en-GB to boostrap it
=> Initialize en-CA content, copying over en-GB

addon/webextension/background/main.js
Fix #4183, this makes the onboarding behaviour for unsupported websites consistent between the "Page actions" menu and the context menu.
=> Fix #4183, make onboarding behaviour consistent

addon/webextension/background/main.js
We discussed stale PRs in triage yesterday, and decided to just land #4342 and fix the linter error async. This PR is that fix.
=> Fix linter error introduced by fix for 4183

server/src/server.js
Wasn't quite sure how to test for errors, but seems fine locally.
=> Fix #3593, Remove obsolete monkeypatch for install-raven.js

addon/webextension/selector/uicontrol.js
`document.documentElement.clientWidth` seems to be more reliable than `window.innerWidth` for dealing with scrollbars on both windows and osx. I'm not sure what other edge cases might be broken by this change, though :-P
For more discussion, see: https://tylercipriani.com/blog/2014/07/12/crossbrowser-javascript-scrollbar-detection/
=> Fix #4147, Avoid including blank scrollbar area in save-visible shots

server/src/config.js
I don't see the gear menu in 'my shots' on stage. Looks like we need to flip a config value to enable it; seems reasonable to just flip the default.
=> Enable FxA via user settings menu

addon/webextension/background/main.js
Slight follow up fix to #3964 PR to filter out download canceled in error logs
=> Fixes #4467 - Filter out download canceled error messages in logs

server/src/pages/shot/crop-tool.js, server/src/pages/shot/drawing-tool.js, server/src/pages/shot/editor.js
=> Move mousemove detection up to the editor.

bin/run-addon
=> Allow bin/run-addon to discover Firefoxes with spaces in the app name

Makefile, bin/build-scripts/delete-us-dup-locales.sh
This keeps us from adding duplicate files to Firefox. Specifically en_CA has no differences from en_US
=> Delete any locale messages.json that match the en_US/messages.json file

addon/bootstrap.js
The 'sessionstore-windows-restored' delay is now applied to all
extensions by the addon management code in Firefox. See bug 1457224
for details.
We still invoke `appStartupDone()` to avoid shutting down before startup is complete (see uses of `appStartupPromise`).
=> Fix #3160, remove app startup delay

addon/bootstrap.js
This includes the mozilla-central commit from https://bugzilla.mozilla.org/show_bug.cgi?id=1466349
Commit is https://hg.mozilla.org/releases/mozilla-beta/rev/4a309778103f
=> Fix #4528, Pass addonData through to embedded WebExtension startup

CHANGELOG.md, bin/build-docker-image, bin/release-version, package.json, server/src/config.js, server/src/dbschema.js, test/server/test_file_management.py
Backport to include changes from #4484.  See #4562.
=> 31.5.0 backport

server/src/pages/shot/crop-tool.js, server/src/pages/shot/drawing-tool.js, server/src/pages/shot/editor-history.js, server/src/pages/shot/editor.js, server/src/pages/shot/highlighter-tool.js, server/src/pages/shot/pen-tool.js
- Ensure drawing canvas always match base canvas' dimensions.
- Scale a component's drawing context only when the canvas has been replaced.
Fix #4453, #4509
=> Calculate pixel ratio from the image's natural size. (#4453, #4509)

server/src/dbschema.js, server/src/server.js
Now that we have potential divergence between the patch level in the code and the patch level in the database, it seems useful to report both values in the `__version__` endpoint. So, `dbSchemaVersion` is now the patch level in the database, and `dbSchemaVersionJS` is the patch level in the server code.
Fixes #4569.
=> Return both DB and JS patch levels in __version__

addon/webextension/manifest.json.template
The relevant permissions were added directly to mozilla-central in bug 1466349.
=> Fix #4603, Add permissions to enable PDF.js and reader mode shots

server/src/watchdog.js
=> Wait to fetch image data a few times in Watchdog.

Makefile, bin/release-version
@g-k Mind taking a look? Not sure how I can verify the built xpi is really signed until this lands in master. Suggestions welcome :-)
=> Fix #4665; Sign dev and stage XPIs with the autograph dev-root

docs/METRICS.md, server/src/pages/shot/editor.js
=> Track undo/redo events

addon/webextension/selector/documentMetadata.js
The `property` attribute is [a white space separated list of values](https://www.w3.org/TR/2008/REC-rdfa-syntax-20081014/#A-property) and not a single value. CSS /querySelectors can handle this using [~=](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).
Some examples and [more context](https://www.ctrl.blog/entry/rdfa-socialmedia-metadata):
<meta property="dc:publisher og:site_name" content="Allizom Media">
<meta property="article:modified_time dc:modified og:updated_time" content="2018-08-28">
=> property is a white space separated list

addon/bootstrap.js, addon/webextension/background/selectorLoader.js, addon/webextension/experiments/screenshots/api.js, addon/webextension/experiments/screenshots/schema.json, addon/webextension/manifest.json.template
Fixes #4802.
* Add a webextension experiment API to Screenshots that exposes app update channel
* Move ESR check from bootstrap to webextension API
Unfortunately, ESR 60 doesn't allow legacy extensions, so there's no way to test this works in that case. But you can set the debugger and see that it returns the correct channel if you test from nightly :-\
=> Move the ESR check from bootstrap into webextension API

addon/bootstrap.js, addon/webextension/background/selectorLoader.js, addon/webextension/experiments/screenshots/api.js, addon/webextension/experiments/screenshots/schema.json
Move the history enabled and upload-disabled checks from bootstrap into the API.
It might make sense to just check all the prefs in a single API call, but this works for now.
This commit fixes #4531, and depends on the two commits from PR #4809.
=> Check some prefs from the API, not from bootstrap

addon/webextension/selector/ui.js
=> Add "dialog" role to addon ui frames

server/src/pages/shot/view.js
When the URL is copy and pasted onto its own line in a [discourse.org](https://discourse.org) forum, the preview looks like this:
[![](https://screenshotscdn.firefoxusercontent.com/images/65241f16-f327-4f8f-a79e-a581088874eb.png)](https://screenshots.firefox.com/p2rtWjzO6zbC7JNf/forum.bors.tech)
If the OpenGraph type is set to "image", it'll actually embed the image directly without any of the superflouous title stuff, the same way it does for other image hosts like imgur.
=> Mark a shot as OpenGraph "image" type

static/css/frame.scss
=> Fix #4893, make top border of "Edit shot title" box visible

.circleci/config.yml, server/db-patches/patch-25-26.sql, server/db-patches/patch-26-25.sql, server/src/dbschema.js, server/src/proxy-url.js, server/src/server.js, test/server/clientlib.py, test/server/pglib.py, test/server/test_signatures.py
This adds signing 'scopes', so that if you get something signed for one scope, you can't use it for another scope. E.g., you can't get a download URL and use that for an authentication key.
This keeps the 'legacy' scope, which is the current single key. This can be used now to make sure everything works when people upgrade, but removed later as people have used to the new specific scopes. But nothing new will be signed with the legacy scope once this is deployed.
This also updates some functions to use async/await.
=> Fix #4882, use different secrets for different signing purposes

.gitignore, server/src/header.js, server/src/pages/creating/view.js, server/src/pages/homepage/view.js, server/src/pages/not-found/view.js, server/src/pages/shot/crop-tool.js, server/src/pages/shot/editor.js, server/src/pages/shot/promo-dialog.js, server/src/pages/shot/text-tool.js, server/src/pages/shotindex/view.js, server/src/reactrender.js, server/src/share-buttons.js, static/css/frame.scss, static/css/home.scss, static/css/partials/_animations.scss, static/css/partials/_delete-confirmation.scss, static/css/partials/_footer.scss, static/css/partials/_header.scss, static/css/partials/_partials.scss, static/css/partials/_share-panel.scss, static/css/partials/_theme.scss, static/css/partials/_variables.scss, static/css/shot-index.scss
Fixes #4845
This aslo reduces a bunch of complexity by getting rid of all the `default-color-scheme` and `inverse-color-scheme` classes peppered throughout the server views.
Also variable-ized most of the color values and drop shadows that were declared as literals in css and updated the default blues to match photon.
=> update color schemes on shot view and shot index view

test/test.js, webextension/background/main.js
=> Fix #hello onboarding

locales/en-US/server.ftl, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, server/src/servershot.js, static/css/shot-index.scss
=> Add synced shot indicator

docs/METRICS.md, locales/en-US/server.ftl, server/src/pages/shotindex/controller.js, server/src/pages/shotindex/model.js, server/src/pages/shotindex/view.js, static/css/shot-index.scss
=> Enable favorite shots on My Shots

webextension/manifest.json.template
The image shown in the new onboarding step (`onboarding-6.png`) should not be loaded by the webextension unless it's explicitly declared in the `web_accessible_resources` part of the manifest. I'm not sure why it's working, but it seems like an upstream bug; by adding it to the manifest, onboarding will continue to work when the bug's fixed.
=> Add new onboarding image to manifest

static/css/inline-selection.scss
In **Linux desktop with dark theme**, default button text color is white or light gray. If button background is set to a light color, button text are not visible. So button text color and background color must both be defined.
Before:
After:
=> Define button color

README.md
I'm not sure we've ever explicitly mentioned the good-first-issue label in our docs. Here's an attempt at a small step towards better instructions for first-time contributors
=> Add contributing info to the docs

server/src/pages/shot/controller.js, server/src/pages/shot/model.js, server/src/pages/shot/shotpage-header.js, server/src/pages/shot/view.js
PR fixes hiding signin banner on non-owned shots if user has logged in on a device with Firefox Account.
Fix involves passing hasFxa prop to shotpag header that has accountId auth value set from cookie instead of isFxaAuthenticated value set in model.js that double checks if accountId cookie is same as associated accountId in database which will be false for non-owned shots
=> Fixes #5074 - Hide Signin banner on non-owned shot if authenticated

server/src/pages/not-found/view.js
Fix of #5074 to hide [signin promo on not found pages](https://github.com/mozilla-services/screenshots/issues/5074#issuecomment-434242854) if a user has accountId cookie
=> Fixes #5074 - Hide signin promo on not found pages if authenticated

locales/en-US/webextension.properties, webextension/selector/ui.js
I think we were wrong to use 'Save' to mean 'Upload', and I don't recall why we went with it in the first place. It could seem like we're desperate to trick people into uploading shots. Let's not give that impression.
=> Change 'save' button to 'upload' button

Makefile
This should cause npm install to be re-run anytime package-lock.json is updated
=> Add package-lock.json to the dependencies on npm install

static/css/frame.scss
Fixes #5068
The fix includes showing full expiration info on all sizes but `small`.
For `small`, the `time-diff` part is removed.
Example:
=> Show expiration info on all screen sizes. Fixes: #5068

CHANGELOG.md, bin/generate-commit-log
Ignore some newly formatted dependency commit messages. Doesn't yet cover all the cases.
=> Update changelog for versions 35 and 36.

locales/en-US/server.ftl
/cc @flodolo @Pike 
I wasn't seeing this as an error/warning on Pontoon or when trying to run <kbd>$ compare-locales --validate l10n.toml .</kbd> locally, but maybe it's a special case because it's in the reference "en-US" locale.
Fixes #5189
=> Add missing "=" for gNoShots in en-US server.ftl file

docs/server-release.md
In anticipation I've already turned off the protected branch.
The `ours` merge strategy only makes things worse IMHO, as it lets things proceed dangerously. OTOH, conflict resolution is also always the wrong thing. `push -f` is genuinely the right thing to do.
=> Advise using push -f to release to server-prod, I've made too many mistakes with merging

package-lock.json
This is a bunch of fixes to `package-lock.json`. First I had to fix a missing version of `har-validator` which caused all installation to fail, then this reverts the `event-stream` package and removes the `flatmap-stream` attack vector.
=> Npm updates

package-lock.json
The issue is minor: https://npmjs.com/advisories/739
This should fix the builds
=> Update the cached-path-relative transitive dependency to get rid of an npm audit warning

server/src/pages/shot/editor.js, server/src/pages/shot/shotpage-header.js, static/css/frame.scss, static/css/partials/_header.scss, static/css/partials/_variables.scss, static/css/settings.scss, static/css/shot-index.scss
This PR provides a bunch of papercut fixes to CSS assocated with accounts feature including:
* Hiding disabled buttons on shot page
* fixing layout nits on settings page when user has avatar of username specified in FxA
* fixes annotation feature so that preview image is at same height
* fixes spacing and layout of upsell ui
* adds a bit of depth to the favorite icon on the shot index page
* fixes the positioning of the shot title editor
* flips the order of the save cancel buttons in editor view to match other button layouts
* Improves spacing of shot subtitles on shot page
=> fast fixes for fxa styles

server/src/pages/hosting-shutdown/model.js, server/src/pages/hosting-shutdown/page.js, server/src/pages/hosting-shutdown/server.js, server/src/pages/hosting-shutdown/view.js, server/src/server.js
This uses /hosting-shutdown, to try to make it clear that only the server is going away, not the other aspects of the product.
The text isn't localized because it isn't written yet, but localization routines are commented-out in the code.
The page looks like this:
There is a followup for text/localization in #5275
=> Fix #5247, put shutdown placeholder page in place

test/addon/browser_screenshots_ui_check.js, webextension/background/main.js, webextension/background/startBackground.js, webextension/experiments/screenshots/api.js
Fixed #5088 and fixes #5235 
The attempt to enable pageAction on reader mode pages was causing CI failures (maybe a Firefox version issue?), and I've removed that commit from this PR.
=> Upstream changes

server/src/promotion-strategy.js
This simply says to never show the promotions (but does not remove the promotion code).
=> Fix #5254 and fix #5253, remove FxA marketing

webextension/manifest.json.template
Soon Firefox will disable add-ons without this, or require people to opt-in
I believe this follows @mixedpuppy's recommendation
=> Fix #5244, use incognito: spanning in manifest

server/src/middleware/csrf.js, test/test.js, webextension/background/main.js, webextension/background/selectorLoader.js, webextension/background/startBackground.js, webextension/selector/ui.js
Also fix #5263, remove My Shots links for non-server-users
Fix #5261, pop open server page for people with indefinite shots
This was a bit of an annoying patch, as anything involving state, several conditionals, timing, and failure conditions of all the above will be. This doesn't include a fix for #5262, but that will be a fairly simple addition to this change.
=> Fix #5260, query user status from server

server/src/server.js
This is to help QA set their shots to indefinite expiration, even though the frontend of the website has removed that functionality.
There's a followup in #5318 to undo this, but I think it will be helpful for QA since they can't otherwise create indefinite shots on the dev server.
=> Implement /api/tmp-do-not-ship-set-all-indefinite

test/addon/browser_screenshots_ui_check.js
I have not been able to determine the origin of this change, but it appears in mozilla-central. It seems purely aesthetic.
=> Fix #5325, copy in upstream test change

package-lock.json, webextension/manifest.json.template
This PR will fail, but it's necessary to enable the pageAction startup method. I think the Firefox version on CI doesn't support the `about:reader*` manifest.json action.
=> [Hold] Fix #5235, enable pageAction on reader mode

bin/update_mozbuild.py
Also changes the base path from ./webextension->webextension, to be ./->, which makes the copying work; I'm not sure why this was necessary or why it worked before, but it made it work this time.
=> Fix #5241, don't ship files in test/ with Firefox
